package com.euthopiar.core.provider

import com.dylibso.chicory.runtime.HostFunction
import com.dylibso.chicory.runtime.ImportValues
import com.dylibso.chicory.runtime.Instance
import com.dylibso.chicory.wasm.Parser
import com.dylibso.chicory.wasm.WasmModule
import com.dylibso.chicory.wasm.types.ValueType
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.json.*
import okhttp3.OkHttpClient
import okhttp3.Request
import java.io.ByteArrayInputStream
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.security.MessageDigest
import java.security.SecureRandom
import java.util.Base64
import java.util.concurrent.ConcurrentHashMap
import javax.crypto.Cipher
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.spec.SecretKeySpec

/**
 * Headless WebAssembly cryptographic engine for 1Shows (https://www.1shows.org).
 *
 * Implements Archetype A (API / Wasm / AES-GCM / PRNG):
 * - Dynamic `makimaDL.wasm` runtime with live manifest loading and offline Base64 fallback.
 * - Dynamic export name resolution (_TH0g, _Tk4p, _pSkr) matching 1Shows rotating hashes.
 * - Vidrock AES-256-GCM native decryption.
 * - Vidy PRNG stream cipher native decryption.
 * - Vidzee multi-audio wasm runtime.
 * - Viduki Main Altcha PoW + Pepper key envelope decryption.
 * - Zero Android SDK dependencies, 100% pure Kotlin JVM (:eup-api sandbox compliant).
 */
object OneShowsWasmEngine {

    private const val SITE_URL = "https://www.1shows.org"
    private const val USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"

    private val json = Json { ignoreUnknownKeys = true; isLenient = true }

    private fun safeLog(tag: String, message: String, t: Throwable? = null) {
        System.err.println("[$tag] $message" + (t?.let { ": ${it.message}" } ?: ""))
    }

    private fun hexToBytes(hex: String): ByteArray {
        val len = hex.length
        val data = ByteArray(len / 2)
        var i = 0
        while (i < len) {
            data[i / 2] = ((Character.digit(hex[i], 16) shl 4) + Character.digit(hex[i + 1], 16)).toByte()
            i += 2
        }
        return data
    }

    /* ---------------------------------------------------------------------- */
    /* Embedded Wasm Fallbacks (100% offline & sandbox resilient)             */
    /* ---------------------------------------------------------------------- */

    private val MAKIMA_DL_B64 = buildString {
        append("AGFzbQEAAAABRQtgAX8Bf2ACf38Bf2ACf38AYAN/f38AYAF/AGAAAGAEf39/fwBgA39/fgBgAAF/YAV/f39/fwF/YAl/f39/f39/f38BfwINAQNlbnYFYWJvcnQABgMxMAEDBQAEAAEAAQABAwECAgAEBAMAAwEABQcFAgIDAAQCBAQGAgUBCAECCQADCgUAAQUDAQABBkAMfwFBwAgLfwFBAAt/AUEAC38BQQALfwFBAAt/AUEAC38BQQALfwFBAAt/AUEAC38BQQALfwFBAAt/AUGImQILBzIGBV9USDBnAC8FX1RrNHAALgVfdVNOWQAsBV9IaXh5ADAFX3BTa3IALQZtZW1vcnkCAAgBJQwBLwq8PDBLACMLQQRrJAsQAyMLQQA2AgAjCyAANgIAIAEgACgCCE8EQEHQFUHwF0GnAUEtEAAACyMLIAA2AgAgACgCBCABai0AACMLQQRqJAsLTQAjC0EEayQLEAMjC0EANgIAIwsgADYCACABIAAoAghPBEBB0BVB8BdBsgFBLRAAAAsjCyAANgIAIAAoAgQgAWogAjoAACMLQQRqJAsLGgAjC0GIGUgEQEGgmQJB0JkCQQFBARAAAAsLPgEBfyMLQQhrJAsQAyMLQgA3AwAjC0EMQQQQCSIBNgIAIwsgATYCBCMLIAEgABAoIgA2AgAjC0EIaiQLIAALIwAgAEUEQA8LIABBFGsiABAKIwhGBEAgABARIwRBAWokBAsLJQAjC0EEayQLEAMjC0EANgIAIwsgADYCACAAKAIIIwtBBGokCwtLACMLQQRrJAsQAyMLQQA2AgAjCyAANgIAIAEgACgCDE8EQEHQFUGgF0HyAEEqEAAACyMLIAA2AgAgACgCBCABai0AACMLQQRqJAsLCgAgACgCBEF8cQujAQEBfyAAQez///8DTwRAQZAUQdAUQYUCQR8QAAALIwEjAk8EQAJAQYAQIQIDQCACECdrIQIjA0UEQCMBQQF0QYAI")
        append("aiQCDAILIAJBAEoNAAsjASMBIwJrQYAISUEKdGokAgsLIwpFBEAQGAsjCiAAQRBqECYiAiABNgIMIAIgADYCECACIwkjCBAdIAIQHiMBaiQBIAJBFGoiAUEAIAD8CwAgAQsKACAAKAIEQQNxC0MAIwtBBGskCxADIwtBADYCACMLIAA2AgAgABAUIAFNBEBB0BVBsBhBzgBBKRAAAAsgACABQQJ0aigCACMLQQRqJAsLSAEBfyABRQRADwsgAUEUayIBEAojCEYEQCAAQRRrIgAQCiIDIwhFRgRAIAAgASACGxARBSMDQQFGIANBA0ZxBEAgARARCwsLC1EBAn8jC0EIayQLEAMjC0IANwMAIwsgARAEIgM2AgADQCABIAJKBEAjCyADNgIEIAMgAiAAIAJqLQAAEAIgAkEBaiECDAELCyMLQQhqJAsgAwvDAQEEfyABKAIAQXxxIgNBgAJJBH8gA0EEdgVBH0H8////AyADIANB/P///wNPGyIDZ2siBEEHayECIAMgBEEEa3ZBEHMLIQQgASgCCCEFIAEoAgQiAwRAIAMgBTYCCAsgBQRAIAUgAzYCBAsgASAAIAJBBHQgBGpBAnRqIgEoAmBGBEAgASAFNgJgIAVFBEAgACACQQJ0aiIBKAIEQX4gBHdxIQMgASADNgIEIANFBEAgACAAKAIAQX4gAndxNgIACwsLC7wCAQV/IAEoAgAhAyABQQRqIAEoAgBBfHFqIgQoAgAiAkEBcQRAIAAgBBAOIAEgA0EEaiACQXxxaiIDNgIAIAFBBGogASgCAEF8cWoiBCgCACECCyADQQJxBEAgAUEEaygCACIBKAIAIQYgACABEA4gASAGQQRqIANBfHFqIgM2AgALIAQgAkECcjYCACAEQQRrIAE2AgAgACADQXxxIgJBgAJJBH8gAkEEdgVBH0H8////AyACIAJB/P///wNPGyICZ2siA0EHayEFIAIgA0EEa3ZBEHMLIgIgBUEE")
        append("dGpBAnRqKAJgIQMgAUEANgIEIAEgAzYCCCADBEAgAyABNgIECyAAIAVBBHQgAmpBAnRqIAE2AmAgACAAKAIAQQEgBXRyNgIAIAAgBUECdGoiACAAKAIEQQEgAnRyNgIECxIAIAAgADYCBCAAIAA2AgggAAuGAQECfyAAIwZGBEAgACgCCCQGCwJAIAAQCCIBRQRAIAAoAggaDAELIAEgACgCCCICNgIIIAIgARAbCyMHIQEgACgCDCICQQJNBH9BAQUgAkHgGCgCAEsEQEHQFUGQFkEVQRwQAAALIAJBAnRB5BhqKAIAQSBxCyECIAAgASMIRUECIAIbEB0LuQEBA38CQAJAAkACQAJAAkACQAJAAkACQCAAQQhrKAIADgkAAQIDBAUGBwgJCw8LDwsPCyAAEB8PCyAAEB8PCyMLQQRrJAsQAyMLQQA2AgAjCyAANgIAIAAoAgQhASMLIAA2AgAgASAAKAIMQQJ0aiECA0AgASACSQRAIAEoAgAiAwRAIAMQBQsgAUEEaiEBDAELCyMLIAA2AgAgACgCABAFIwtBBGokCw8LIAAQIQ8LIAAQIQ8LDwsAC+IJAQx/IwtBEGskCxADIwtCADcDACMLQgA3AwgjC0EQEAQiAzYCAANAIARBEEgEQCMLIAM2AgQjCyABNgIIIAMgBCABIAQQARACIARBAWohBAwBCwtBACEBA0AgAUEESARAIwsgADYCBCAAIAEQCyEEIwsgAzYCBCMLIAM2AgggAyABQQJ0IgUgAyAFEAEgBEEYdnMQAiMLIAM2AgQjCyADNgIIIAMgBUEBaiIGIAMgBhABIARBEHZzEAIjCyADNgIEIwsgAzYCCCADIAVBAmoiBiADIAYQASAEQQh2cxACIwsgAzYCBCMLIAM2AgggAyAFQQNqIgUgAyAFEAEgBHMQAiABQQFqIQEMAQsLQQEhBANAIARBDkwEQEEAIQEDQCABQRBIBEAjCyADNgIEIwtBoBI2Aggj")
        append("CyADNgIMIAMgAUGgEiADIAEQARAHEAIgAUEBaiEBDAELCyMLIAM2AgQgA0EBEAEhASMLIAM2AgQjCyADNgIIIANBASADQQUQARACIwsgAzYCBCMLIAM2AgggA0EFIANBCRABEAIjCyADNgIEIwsgAzYCCCADQQkgA0ENEAEQAiMLIAM2AgQgA0ENIAEQAiMLIAM2AgQgA0ECEAEhASMLIAM2AgQgA0EGEAEhBSMLIAM2AgQjCyADNgIIIANBAiADQQoQARACIwsgAzYCBCMLIAM2AgggA0EGIANBDhABEAIjCyADNgIEIANBCiABEAIjCyADNgIEIANBDiAFEAIjCyADNgIEIANBDxABIQEjCyADNgIEIwsgAzYCCCADQQ8gA0ELEAEQAiMLIAM2AgQjCyADNgIIIANBCyADQQcQARACIwsgAzYCBCMLIAM2AgggA0EHIANBAxABEAIjCyADNgIEIANBAyABEAIgBEEOSARAQQAhAQNAIAFBBEgEQCMLIAM2AgQgAyABQQJ0IggQASELIwsgAzYCBCADIAhBAWoiBRABIQwjCyADNgIEIAMgCEECaiIGEAEhCSMLIAM2AgQgAyAIQQNqIgcQASIKIAsgDHMiDSAJc3MhDiMLIAM2AgQgAyAIIA1B/wFxQQd2QRtsIA1BAXRzQf8BcSALIA5zc0H/AXEQAiMLIAM2AgQgAyAFIAkgDHMiBUH/AXFBB3ZBG2wgBUEBdHNB/wFxIAwgDnNzQf8BcRACIwsgAzYCBCADIAYgCSAKcyIFQf8BcUEHdkEbbCAFQQF0c0H/AXEgCSAOc3NB/wFxEAIjCyADNgIEIAMgByAKIAtzIgVB/wFxQQd2QRtsIAVBAXRzQf8BcSAKIA5zc0H/AXEQAiABQQFqIQEMAQsLC0EAIQEDQCABQQRIBEAjCyAANgIEIAAgBEECdCABahALIQUjCyADNgIEIwsgAzYCCCADIAFBAnQiBiADIAYQASAFQRh2")
        append("cxACIwsgAzYCBCMLIAM2AgggAyAGQQFqIgcgAyAHEAEgBUEQdnMQAiMLIAM2AgQjCyADNgIIIAMgBkECaiIHIAMgBxABIAVBCHZzEAIjCyADNgIEIwsgAzYCCCADIAZBA2oiBiADIAYQASAFcxACIAFBAWohAQwBCwsgBEEBaiEEDAELC0EAIQADQCAAQRBIBEAjCyACNgIEIwsgAzYCCCACIAAgAyAAEAEQAiAAQQFqIQAMAQsLIwtBEGokCwsNACAAQRRrKAIQQQJ2C0wAIwtBBGskCxADIwtBADYCACMLIAA2AgAgABAUIAFNBEBB0BVBsBhB3QBBKRAAAAsjCyAANgIAIAAgAUECdGogAjYCACMLQQRqJAsLjgEBAn8gAUGAAkkEfyABQQR2BUEfIAEQFyIBZ2siA0EHayECIAEgA0EEa3ZBEHMLIQEgACACQQJ0aigCBEF/IAF0cSIBBH8gACABaCACQQR0akECdGooAmAFIAAoAgBBfyACQQFqdHEiAQR/IAAgACABaCIAQQJ0aigCBGggAEEEdGpBAnRqKAJgBUEACwsLHQAgAEEBQRsgAGdrdGpBAWsgACAAQf7///8BSRsLlwEBAn8/ACIAQQBMBH9BASAAa0AAQQBIBUEACwRAAAtBkJkCQQA2AgBBsKUCQQA2AgADQCABQRdJBEAgAUECdEGQmQJqQQA2AgRBACEAA0AgAEEQSQRAIAFBBHQgAGpBAnRBkJkCakEANgJgIABBAWohAAwBCwsgAUEBaiEBDAELC0GQmQJBtKUCPwCsQhCGEBlBkJkCJAoLhgEBA38gAUETakFwcUEEayEBIAAoAqAMIgMEQCABQRBrIgUgA0YEQCADKAIAIQQgBSEBCwsgAqdBcHEgAWsiA0EUSQRADwsgASAEQQJxIANBCGsiA0EBcnI2AgAgAUEANgIEIAFBADYCCCABQQRqIANqIgNBAjYCACAAIAM2AqAMIAAgARAPC14BAn8j")
        append("ACIABEAgABAFC0GQDRAFQYAOEAVB0A8QBUGgEhAFQfASEAVB0BUQBUGgExAFQZAUEAUjBSIBEAghAANAIAAgAUcEQCAAEAoaIABBFGoQEiAAEAghAAwBCwsLEgAgACABIAAoAgRBA3FyNgIECxIAIAAgACgCBEF8cSABcjYCBAspAQF/IAEoAgghAyAAIAEgAnI2AgQgACADNgIIIAMgABAbIAEgADYCCAsNACAAKAIAQXxxQQRqCwkAIAAoAgAQBQsRACAAIAE2AgAgACABQQAQDAsnACMLQQRrJAsQAyMLQQA2AgAjCyAANgIAIAAoAgAQBSMLQQRqJAsLZgEBfyMLQQhrJAsQAyMLQgA3AwBBDyEBA0AgAUEMTgRAAkAjCyAANgIAIwsgADYCBCAAIAEgACABEAFBAWpB/wFxEAIjCyAANgIAIAAgARABDQAgAUEBayEBDAILCwsjC0EIaiQLC5sBAQR/IwtBCGskCxADIwtCADcDAANAIAMgBUoEQEEQIAMgBWsiBCAEQRBOGyEGQQAhBANAIAQgBkgEQCMLIAA2AgAjCyAANgIEIAAgBBABIQcjCyACNgIEIAAgBCACIAQgBWoQASAHcxACIARBAWohBAwBCwsjCyAANgIAIwsgATYCBCAAIAEQJCAFQRBqIQUMAQsLIwtBCGokCwuHAwEHfyMLQRBrJAsQAyMLQgA3AwAjC0IANwMIIwtBEBAEIgc2AgAjC0EQEAQiCDYCBANAIAJBEEgEQCMLIAg2AggjCyAANgIMIAggAiAAIAIQARACIAJBAWohAgwBCwsDQCAFQYABSARAIwsgATYCCCABIAVBA3YQAUEHIAVBB3FrQQdxdkEBcQRAQQAhAgNAIAJBEEgEQCMLIAc2AggjCyAHNgIMIAcgAhABIQMjCyAINgIMIAcgAiAIIAIQASADcxACIAJBAWohAgwBCwsLQQAhAkEAIQYDQCAGQRBIBEAjCyAINgIIIAggBhAB")
        append("QQFxIwsgCDYCCCMLIAg2AgwgCCAGIAJBB3QgCCAGEAFBAXZyQf8BcRACIQIgBkEBaiEGDAELCyACBEAjCyAINgIIIwsgCDYCDCAIQQAgCEEAEAFB4QFzEAILIAVBAWohBQwBCwsDQCAEQRBIBEAjCyAANgIIIwsgBzYCDCAAIAQgByAEEAEQAiAEQQFqIQQMAQsLIwtBEGokCwsmAD8AQRB0QYiZAmtBAXYkAkGAFRAQJAVBoBUQECQHQbAWEBAkCQuTAgEDfyABQfz///8DSwRAQZAUQeAWQc0DQR0QAAALIABBDCABQRNqQXBxQQRrIAFBDE0bIgMQFiIBRQRAQQQgACgCoAw/ACIBQRB0QQRrR3QgAxAXIAMgA0GAAk8bakH//wNqQYCAfHFBEHYhAiABIAIgASACShtAAEEASARAIAJAAEEASARAAAsLIAAgAUEQdD8ArEIQhhAZIAAgAxAWIQELIAEoAgAaIAAgARAOIAEoAgAiAkF8cSADayIEQRBPBEAgASADIAJBAnFyNgIAIAFBBGogA2oiAiAEQQRrQQFyNgIAIAAgAhAPBSABIAJBfnE2AgAgAUEEaiABKAIAQXxxaiIAIAAoAgBBfXE2AgALIAEL/wIBAn8CQAJAAkACQCMDDgMAAQIDC0EBJANBACQEEBojByQGIwQPCyMIRSEBIwYQCCEAA0AgACMHRwRAIAAkBiAAEAogAUcEQCAAIAEQHEEAJAQgAEEUahASIwQPCyAAEAghAAwBCwtBACQEEBojBhAIIwdGBEAjCyEAA0AgAEGImQJJBEAgACgCABAFIABBBGohAAwBCwsjBhAIIQADQCAAIwdHBEAgABAKIAFHBEAgACABEBwgAEEUahASCyAAEAghAAwBCwsjCSEAIwckCSAAJAcgASQIIAAQCCQGQQIkAwsjBA8LIwYiACMHRwRAIAAQCCQGIAAQChogAEGImQJJBEAgAEEANgIEIABBADYCCAUjASAA")
        append("EB5rJAEgAEEEaiIAQYiZAk8EQCMKRQRAEBgLIABBBGshASAAQQ9xQQEgABsEf0EBBSABKAIAQQFxCxogASABKAIAQQFyNgIAIwogARAPCwtBCg8LIwcjBzYCBCMHIwc2AghBACQDC0EAC7YBAQF/IwtBEGskCxADIwtCADcDACMLQgA3AwggAEUEQCMLQQxBAxAJIgA2AgALIwsgADYCBCAAQQAQICMLIAA2AgQgAEEANgIEIwsgADYCBCAAQQA2AgggAUH8////A0sEQEGgE0HQE0ETQTkQAAALIwsgAUEBEAkiAjYCCCMLIAA2AgQjCyACNgIMIAAgAhAgIwsgADYCBCAAIAI2AgQjCyAANgIEIAAgATYCCCMLQRBqJAsgAAvwAQEDfyMLQQRrJAsQAyMLQQA2AgAjCyAANgIAIAEgACgCCCICQQJ2SwRAIAFB/////wBLBEBBoBNBoBdBE0EwEAAACyMLIAA2AgACQEH8////AyACQQF0IgIgAkH8////A08bIgJBCCABIAFBCE0bQQJ0IgEgASACSRsiAyAAKAIAIgJBFGsiBCgCAEF8cUEQa00EQCAEIAM2AhAgAiEBDAELIAMgBCgCDBAJIgEgAiADIAQoAhAiBCADIARJG/wKAAALIAEgAkcEQCAAIAE2AgAgACABNgIEIAAgAUEAEAwLIAAgAzYCCAsjC0EEaiQLC9cHAgt/A34jC0E8ayQLEAMjC0EAQTz8CwAjCyABNgIAAkACQCABEAZBDEcNACMLIAM2AgAgAxAGQRBHDQAjCyAANgIAIwsgABArIgg2AgQjC0EQEAQiADYCCCMLQRAQBCIONgIMIwsgCDYCACMLIAA2AhAjCyAONgIUIAggACAOEBMjC0EQEAQiDzYCGANAIAVBDEgEQCMLIA82AgAjCyABNgIQIA8gBSABIAUQARACIAVBAWohBQwBCwsjCyAPNgIAIA9BD0EBEAIjC0EQEAQiADYCHCMLIAA2")
        append("AgAjCyAONgIQIwsgBDYCFCMLIAQ2AiAgACAOIAQgBBAGECMjCyAANgIAIwsgDjYCECMLIAI2AhQjCyACNgIgIAAgDiACIAIQBhAjIwtBEBAEIgE2AiQjCyAENgIAIAQQBqxCA4YhECMLIAI2AgAgAhAGrEIDhiERA0AgCUEISARAIwsgATYCACABQQcgCWsgECAJQQN0rCISiKdB/wFxEAIjCyABNgIAIAFBDyAJayARIBKIp0H/AXEQAiAJQQFqIQkMAQsLA0AgCkEQSARAIwsgADYCACMLIAA2AhAgACAKEAEhBCMLIAE2AhAgACAKIAEgChABIARzEAIgCkEBaiEKDAELCyMLIAA2AgAjCyAONgIQIAAgDhAkIwtBEBAEIgE2AigjCyAINgIAIwsgDzYCECMLIAE2AhQgCCAPIAEQEyMLQRAQBCIENgIsA0AgC0EQSARAIwsgBDYCACMLIAA2AhAgACALEAEhBSMLIAE2AhAgBCALIAEgCxABIAVzQf8BcRACIAtBAWohCwwBCwsDQCAGQRBIBEAjCyAENgIAIAQgBhABIQAjCyADNgIAIAcgAyAGEAEgAHNyIQcgBkEBaiEGDAELCyAHQf8BcQ0AIwsgAjYCACMLIAIQBhAEIgA2AjAjC0EQEAQiAzYCNANAIA1BEEgEQCMLIAM2AgAjCyAPNgIQIAMgDSAPIA0QARACIA1BAWohDQwBCwsjCyADNgIAIAMQIiMLQRAQBCIENgI4A0AjCyACNgIAIAIQBiAMSgRAIwsgCDYCACMLIAM2AhAjCyAENgIUIAggAyAEEBMjCyACNgIAIAIQBiAMa0EQTgR/QRAFIwsgAjYCACACEAYgDGsLIQVBACEBA0AgASAFSARAIwsgADYCACMLIAI2AhAgAiABIAxqIgYQASEHIwsgBDYCECAAIAYgBCABEAEgB3NB/wFxEAIgAUEBaiEBDAELCyAMQRBqIQwjCyADNgIAIAMQIgwBCwsM")
        append("AQtBACEACyMLQTxqJAsgAAuJBAEEfyMLQQxrJAsQAyMLQgA3AwAjC0EANgIIIwsjC0EEayQLEAMjC0EANgIAIwtB8AFBCBAJIgI2AgAjC0EEaiQLIAI2AgADQCABQQhIBEAjCyACNgIEIwsgADYCCCAAIAFBAnQiAxABQRh0IwsgADYCCCAAIANBAWoQAUEQdHIjCyAANgIIIAAgA0ECahABQQh0ciEEIwsgADYCCCACIAEgACADQQNqEAEgBHIQFSABQQFqIQEMAQsLQQghAANAIABBPEgEQCMLIAI2AgQgAiAAQQFrEAshASAAQQdxBH8gAEEIb0EERgR/IwtBoBI2AgRBoBIgAUEYdhAHQRh0IwtBoBI2AgRBoBIgAUEQdkH/AXEQB0EQdHIjC0GgEjYCBEGgEiABQQh2Qf8BcRAHQQh0ciEDIwtBoBI2AgRBoBIgAUH/AXEQByADcgUgAQsFIwtBoBI2AgRBoBIgAUEIdCABQRh2ciIBQRh2EAdBGHQjC0GgEjYCBEGgEiABQRB2Qf8BcRAHQRB0ciMLQaASNgIEQaASIAFBCHZB/wFxEAdBCHRyIQMjC0GgEjYCBEGgEiABQf8BcRAHIANyIwtB8BI2AgRB8BIgAEEIbRAHQRh0cwshASMLIAI2AgQjCyACNgIIIAIgACACIABBCGsQCyABcxAVIABBAWohAAwBCwsjC0EMaiQLIAILDAAgACABaiACOgAAC7UDACMLQTBrJAsQAyMLQQBBMPwLACMLIAAgARANIgE2AgAjCyACIAMQDSICNgIEIwsgBCAFEA0iAzYCCCMLIAYgBxANIgQ2AgwjC0EgEAQiBTYCEEEAIQADQCAAQSBIBEAjCyAFNgIUIwtBkA02AhgjC0HQDzYCHCMLQQRrJAsQAyMLQQA2AgAjC0HQDzYCACAAQdwPKAIATwRAQdAVQaAXQfIAQSoQAAALIwtB0A82AgBB1A8oAgAgAEECdGooAgAhBiML")
        append("QQRqJAtBkA0gBhAHIQYjC0GADjYCGCAFIABBgA4gABAHIAZzQf8BcRACIABBAWohAAwBCwsjCyAFNgIUIwsgAjYCGCMLIAM2AhwjCyAENgIgIwsgATYCJCMLIAUgAiADIAQgARAqIgA2AihBACECA0AgAkEgSARAIwsgBTYCFCAFIAJBABACIAJBAWohAgwBCwsgAEUEQCMLQTBqJAtBfw8LIwsgADYCLEEAIQEDQCMLIAA2AhQgABAGIAFKBEAjCyAANgIUIAEgCGogACABEAE6AAAgAUEBaiEBDAELCyMLIAA2AhQgABAGIwtBMGokCwthAQJ/IwtBBGskCxADIwtBADYCACMLQQBBARAJIgBB0BdBAPwKAAAgADYCAEEQQQUQCSIBIAA2AgAgASAAQQAQDCABIAA2AgQgAUEANgIIIAFBADYCDCMLQQRqJAsgASQAC6QBAQN/IwtBDGskCxADIwtCADcDACMLQQA2AggjCyAAEAQiAzYCACMLIwAiAjYCBCMLIAM2AggjC0EEayQLEAMjC0EANgIAIwsgAjYCACACIAIoAgwiAEEBaiIBECkjCyACNgIAIAIoAgQgAEECdGogAzYCACACIANBARAMIwsgAjYCACACIAE2AgwjC0EEaiQLIwsgAzYCBCADKAIEIwtBDGokCwsKACAAIAFqLQAACwuyDi8AQYwICwEcAEGYCAsBAQBBrAgLASwAQbgICw4FAAAAEAAAACAEAAAgBABB3AgLAhwCAEHoCAuIBAEAAAAAAgAAhOfTh+GtLou/hIypewCCKyFtWUp5tCEwQIk+0gnhJw9h4QCnGV9V+mCzHoS+xc8cM2pRWMmYGDD/ZFreyel4yZIp9h0hPaGkdPjLoDmsyH8zx62dlLYQjKQ+k/6N3CKX2AlfJNjnFNJet1D/f0UiHTtppheML7ZgCGZsZ+LmUQiuEk1RhS5op0LZWqCNdk7q2mWF9X12jUC4m1C3/E+uha+7QDyU")
        append("5czCh9uJ/8Yp/yfqLiIXSCyNDn0wu/tpFybdc+YCRZ4tplB/qUZc9eCbk/ZOkFCM6Ao+qeY4HmNtqFHKoMbZ9AXooukPAYyp4LrIpdOGLH0rjLCQ4k+WxG5bYU2q7mQi4wkPw78a6sPf5uP73eQsyJ2f5BM7bI0DbG73T4dseczMVoRSWrL3X8Zyi5U7uJnh15SrHphWcFkXsibnZJS8B8YGPpCH9EISfLnP2OsA2iyLhxolnRQ4aWF12eiR9nRGuIoegHWlcUgIxDz7TAqvkf5Ms5soIWgW+Y1WdWoV5msWbIgQvOZO95UhiWGe0jbqSq5bjWdH/pWqPvTGPwqnSxL8/tPcSd11AWDKWUOxwN4PpUjh4/A84SrB7gMcE2f98HsyL7ckeqYGFgKbBEkawMzyiMH4Fb8PM9/5Fvk1VcdDHZqaJDu5n5DhOgP1TeSHwl6xDKevfyWQFKQAQfwMCwEsAEGIDQsWBgAAABAAAABwBAAAcAQAAAACAAAAAgBBrA0LATwAQbgNCygBAAAAIAAAAFHtkiORKae3HOyo7CdFPEgG58AWXcBXP6x3Z/InUwHWAEHsDQsBLABB+A0LFQYAAAAQAAAAwAYAAMAGAAAgAAAAIABBnA4LAZwAQagOC4UBAQAAAIAAAACpAAAASwAAAIEBAAD/AAAAswEAADgAAADDAAAABAAAAKQAAADWAAAADwAAAJ4AAABiAQAAKwEAAHcBAACwAAAAVgEAAGcBAAD0AAAAgQAAAJsBAADKAQAAKAAAABUBAADcAAAAGgAAABwAAAB7AQAAlgEAAKMAAADTAAAAlgBBvA8LASwAQcgPCxUHAAAAEAAAADAHAAAwBwAAgAAAACAAQewPCwIcAQBB+A8LiAIBAAAAAAEAAGN8d3vya2/FMAFnK/7Xq3bKgsl9+llH8K3Uoq+cpHLAt/2TJjY/98w0peXxcdgxFQTHI8MYlgWaBxKA4usnsnUJgywaG25aoFI71rMp")
        append("4y+EU9EA7SD8sVtqy745SkxYz9DvqvtDTTOFRfkCf1A8n6hRo0CPkp049by22iEQ//PSzQwT7F+XRBfEp349ZF0Zc2CBT9wiKpCIRu64FN5eC9vgMjoKSQYkXMLTrGKRleR558g3bY3VTqlsVvTqZXquCLp4JS4cprTG6N10H0u9i4pwPrVmSAP2DmE1V7mGwR2e4fiYEWnZjpSbHofpzlUo34yhiQ2/5kJoQZktD7BUuxYAQYwSCwEsAEGYEgsWBgAAABAAAAAACAAAAAgAAAABAAAAAQBBvBILARwAQcgSCxMBAAAACwAAAAABAgQIECBAgBs2AEHcEgsBLABB6BILFQYAAAAQAAAAUAkAAFAJAAALAAAACwBBjBMLASwAQZgTCyMCAAAAHAAAAEkAbgB2AGEAbABpAGQAIABsAGUAbgBnAHQAaABBvBMLATwAQcgTCy0CAAAAJgAAAH4AbABpAGIALwBhAHIAcgBhAHkAYgB1AGYAZgBlAHIALgB0AHMAQfwTCwE8AEGIFAsvAgAAACgAAABBAGwAbABvAGMAYQB0AGkAbwBuACAAdABvAG8AIABsAGEAcgBnAGUAQbwUCwE8AEHIFAsnAgAAACAAAAB+AGwAaQBiAC8AcgB0AC8AaQB0AGMAbQBzAC4AdABzAEG8FQsBPABByBULKwIAAAAkAAAASQBuAGQAZQB4ACAAbwB1AHQAIABvAGYAIAByAGEAbgBnAGUAQfwVCwEsAEGIFgsbAgAAABQAAAB+AGwAaQBiAC8AcgB0AC4AdABzAEHMFgsBPABB2BYLJQIAAAAeAAAAfgBsAGkAYgAvAHIAdAAvAHQAbABzAGYALgB0AHMAQYwXCwEsAEGYFwshAgAAABoAAAB+AGwAaQBiAC8AYQByAHIAYQB5AC4AdABzAEG8FwsBHABByBcLAQEAQdwXCwE8AEHoFwsrAgAAACQAAAB+AGwAaQBiAC8AdAB5AHAAZQBkAGEAcgBy")
        append("AGEAeQAuAHQAcwBBnBgLATwAQagYCy0CAAAAJgAAAH4AbABpAGIALwBzAHQAYQB0AGkAYwBhAHIAcgBhAHkALgB0AHMAQeAYCyYJAAAAIAAAACAAAAAgAAAAAAAAAEEAAAACQQAAQgAAAAIJAAAkAQ==")
    }

    private val VIDZEE_B64 = buildString {
        append("AGFzbQEAAAABPgtgAX8Bf2ACf38Bf2ABfwBgAn9/AGADf39/AGAAAGAEf39/fwBgBH9/f38Bf2ADf39/AX9gA39/fgBgAAF/Ag0BA2VudgVhYm9ydAAGAygnAgEAAAQBAAEDBAADBQAAAgMHAAEAAAQIAwEJAgIBBQAAAgEABQoBBQMBAAEGJgd/AUEAC38BQQALfwFBAAt/AUEAC38BQQALfwFBAAt/AEGA2wALB0gHB2RlY3J5cHQAJwVfX25ldwAGBV9fcGluACQHX191bnBpbgAiCV9fY29sbGVjdAAlC19fcnR0aV9iYXNlAwYGbWVtb3J5AgAIAR8MAqkBCogkJyUAIABFBEAPCyAAQRRrIgAQByMCRgRAIAAQECAAIwUjAkUQCgsLCgAgACABai0AAAsKACAAKAIEQXxxCw0AIABBFGsoAhBBAXYLDAAgACABaiACOgAAC1MBAX8gAEHs////A0sEQEHwDEGwDUH9AEEeEAAACyMARQRAEA0LIwAgAEEQahAaIgIgATYCDCACIAA2AhAgAiMBIwIQCiACEAsjA2okAyACQRRqCwoAIAAoAgRBA3ELKQAgACAAIAFBCHZqLQAAQQV0aiABQf8BcUEDdmotAAAgAUEHcXZBAXELwwEBBH8gASgCAEF8cSIDQYACSQR/IANBBHYFQR9B/P///wMgAyADQfz///8DTxsiA2drIgRBB2shAiADIARBBGt2QRBzCyEEIAEoAgghBSABKAIEIgMEQCADIAU2AggLIAUEQCAFIAM2AgQLIAEgACACQQR0IARqQQJ0aiIBKAJgRgRAIAEgBTYCYCAFRQRAIAAgAkECdGoiASgCBEF+IAR3cSEDIAEgAzYCBCADRQRAIAAgACgCAEF+IAJ3cTYCAAsLCwspAQF/IAEoAgghAyAAIAEgAnI2AgQgACADNgIIIAMgABARIAEgADYCCAsNACAAKAIAQXxxQQRqC7wCAQV/IAEoAgAhAyAB")
        append("QQRqIAEoAgBBfHFqIgQoAgAiAkEBcQRAIAAgBBAJIAEgA0EEaiACQXxxaiIDNgIAIAFBBGogASgCAEF8cWoiBCgCACECCyADQQJxBEAgAUEEaygCACIBKAIAIQYgACABEAkgASAGQQRqIANBfHFqIgM2AgALIAQgAkECcjYCACAEQQRrIAE2AgAgACADQXxxIgJBgAJJBH8gAkEEdgVBH0H8////AyACIAJB/P///wNPGyICZ2siA0EHayEFIAIgA0EEa3ZBEHMLIgIgBUEEdGpBAnRqKAJgIQMgAUEANgIEIAEgAzYCCCADBEAgAyABNgIECyAAIAVBBHQgAmpBAnRqIAE2AmAgACAAKAIAQQEgBXRyNgIAIAAgBUECdGoiACAAKAIEQQEgAnRyNgIEC5cBAQJ/PwAiAEEATAR/QQEgAGtAAEEASAVBAAsEQAALQbDbAEEANgIAQdDnAEEANgIAA0AgAUEXSQRAIAFBAnRBsNsAakEANgIEQQAhAANAIABBEEkEQCABQQR0IABqQQJ0QbDbAGpBADYCYCAAQQFqIQAMAQsLIAFBAWohAQwBCwtBsNsAQdTnAD8ArEIQhhAbQbDbACQACyYBAX8gAEEEayEBIABBD3FBASAAGwR/QQEFIAEoAgBBAXELGiABCxIAIAAgADYCBCAAIAA2AgggAAsnAQF/IAAQAyIBRQRAIAAoAggaDwsgASAAKAIIIgA2AgggACABEBELEgAgACABIAAoAgRBA3FyNgIEC0kBAX8gACABQQF0aiEBA0AgAyIAQQFrIQMgAARAIAEvAQAiACACLwEAIgRHBEAgACAEaw8LIAFBAmohASACQQJqIQIMAQsLQQALbgECf0EMQQYQBiIBRQRAQQxBAxAGIQELIAFBADYCACABQQA2AgQgAUEANgIIIABB/P///wNLBEBB4NcAQZDYAEETQTkQAAALIABBARAGIgJBACAA/AsAIAEgAjYCACABIAI2AgQg")
        append("ASAANgIIIAELjgEBAn8gAUGAAkkEfyABQQR2BUEfIAEQFSIBZ2siA0EHayECIAEgA0EEa3ZBEHMLIQEgACACQQJ0aigCBEF/IAF0cSIBBH8gACABaCACQQR0akECdGooAmAFIAAoAgBBfyACQQFqdHEiAQR/IAAgACABaCIAQQJ0aigCBGggAEEEdGpBAnRqKAJgBUEACwsLHQAgAEEBQRsgAGdrdGpBAWsgACAAQf7///8BSRsLLwAgAEH8////A0sEQEHwDEHwDUHNA0EdEAAAC0EMIABBE2pBcHFBBGsgAEEMTRsLZwECfyABKAIAIgNBfHEgAmsiBEEQTwRAIAEgAiADQQJxcjYCACABQQRqIAJqIgEgBEEEa0EBcjYCACAAIAEQDAUgASADQX5xNgIAIAFBBGogASgCAEF8cWoiACAAKAIAQX1xNgIACwswACAAIAIQGiICQQRqIAFBBGogASgCAEF8cfwKAAAgAUGk2wBPBEAgACABEBkLIAILFQAgASABKAIAQQFyNgIAIAAgARAMC48BAQJ/IAAgARAWIgIQFCIBRQRAQQQgACgCoAw/ACIBQRB0QQRrR3QgAhAVIAIgAkGAAk8bakH//wNqQYCAfHFBEHYhAyABIAMgASADShtAAEEASARAIANAAEEASARAAAsLIAAgAUEQdD8ArEIQhhAbIAAgAhAUIQELIAEoAgAaIAAgARAJIAAgASACEBcgAQuGAQEDfyABQRNqQXBxQQRrIQEgACgCoAwiAwRAIAFBEGsiBSADRgRAIAMoAgAhBCAFIQELCyACp0FwcSABayIDQRRJBEAPCyABIARBAnEgA0EIayIDQQFycjYCACABQQA2AgQgAUEANgIIIAFBBGogA2oiA0ECNgIAIAAgAzYCoAwgACABEAwLhQEBA38CQAJAAkACQAJAAkACQAJAAkAgAEEIaygCAA4IAAECAwQFBgcICw8LDwsPCyAAEB0PCyAAKAIAEAEP")
        append("CyAAKAIEIgEgACgCDEECdGohAgNAIAEgAkkEQCABKAIAIgMEQCADEAELIAFBBGohAQwBCwsgACgCABABDwsgABAdDwsPCwALCQAgACgCABABC0MAIAEgACgCDE8EQEHw1QBBsNYAQfIAQSoQAAALIAAoAgQgAUECdGooAgAiAEUEQEHg1gBBsNYAQfYAQSgQAAALIAALGQBBoA4QDyQBQYDaABAPJARB4NoAEA8kBQv9AQEGfyAAIgFBCHYiAkHMzgBqLQAAIAJBlDJqLQAAQdYAbEGUMmogAEH/AXEiA0EDbmotAAAgA0EDcEECdEGAxwBqKAIAbEELdkEGcGpBAnRBjMcAaigCACICQf8BcSEAIAJBCHUhAgJAIABBAkkNACACQf8BcSEAIAJBCHYhAgNAIAAEQCAAQQF2IgYgAmpBAXRBzNIAaiIELQAAIgUgA0YEfyAELQABQQJ0QYzHAGooAgAiAkH/AXEhACACQQh1IQIgAEECSQ0DIAFBAWoPBSADIAVJBH8gBgUgAiAGaiECIAAgBmsLCyEADAELCyABDwsgASACQQAgAGtxagvABgEKfyAAEAQiCEUEQCAADwsgCEECdEECEAYhBwNAIAMgCEkEQCAAIANBAXRqIgEvAQAiAkEHdgRAAkAgAkH/rwNrQYEISSADIAhBAWtJcQRAIAEvAQIiBEH/twNrQYEISQRAIANBAWohAyAEQf8HcSACIgFB/wdxQQp0ckGAgARqIgJBgIAITwRAIAcgBUEBdGogASAEQRB0cjYCACAFQQFqIQUMAwsLCyACQbACRgRAIAcgBUEBdGpB6YCcGDYCACAFQQFqIQUFIAJBowdGBEAgCEEBSwRAQQAhASADIgJBHmsiBEEAIARBAE4bIQkCQANAIAIgCUoEQEF/IQYCQCACQQBMDQAgACACQQFrQQF0ai8BACIEQYD4A3FBgLgDRiACQQJrIgZBAE5xBEAgBEH/B3EgACAGQQF0ai8B")
        append("ACIKQf8HcUEKdGpBgIAEaiEGIApBgPgDcUGAsANGDQELQf3/AyAEIARBgPADcUGAsANGGyEGCyAGQfCDOEkEf0G0DiAGEAgFQQALRQRAQQAhBCAGQYrjB0kEf0H0JSAGEAgFQQALRQ0DQQEhAQsgAiAGQYCABE5BAWprIQIMAQsLQQAhBCABRQ0AIANBAWoiAkEeaiIBIAggASAISBshBANAIAIgBEgEQCAAIAJBAXRqIgYvAQAiAUGA+ANxQYCwA0YgAkEBaiAIR3EEQCAGLwECIgZBgPgDcUGAuANGBEAgAUEKdCAGakGAuP8aayEBCwsgAUHwgzhJBH9BtA4gARAIBUEAC0UEQCABQYrjB0kEf0H0JSABEAgFQQALRSEEDAMLIAIgAUGAgARPQQFqaiECDAELC0EBIQQLBUEAIQQLIAcgBUEBdGpBwgdBwwcgBBs7AQAFIAJBtskAa0EZTQRAIAcgBUEBdGogAkEaajsBAAUgAhAgQf///wBxIgFBgIAESQRAIAcgBUEBdGogATsBAAUgByAFQQF0aiABQYCABGsiAUEKdkGAsANyIAFB/wdxQYC4A3JBEHRyNgIAIAVBAWohBQsLCwsLBSAHIAVBAXRqIAIgAkHBAGtBGklBBXRyOwEACyADQQFqIQMgBUEBaiEFDAELCyAHIAVBAXQQIwszACAARQRADwsgAEEUayIAEAdBA0cEQEGw2gBBsA1BwwFBBRAAAAsgABAQIAAjASMCEAoLsAIBB38gAEEUayECIABBpNsASQRAIAEgAigCDBAGIgMgACABIAIoAhAiACAAIAFLG/wKAAAgAw8LIAFB7P///wNLBEBB8AxBsA1BjwFBHhAAAAsjAyACEAtrJAMjAEUEQBANCyABQRBqIQMgAEEQayIAQaTbAEkEQCMAIAAQDiADEBghAAUjACEEIAAQDiEAAkACQCADEBYiBiAAKAIAIgdBfHEiBU0NACAAQQRqIAAoAgBBfHFq")
        append("IgIoAgAiCEEBcQRAIAVBBGogCEF8cWoiBSAGTwRAIAQgAhAJIAAgB0EDcSAFcjYCAAwCCwsgBCAAIAMQGCEADAELIAQgACAGEBcLCyAAQRRqIgBBFGsiAiABNgIQIAIQAyACNgIIIAIoAgggAhARIAIQCyMDaiQDIAALNQEBfyAABEAgAEEUayIBEAdBA0YEQEHQ2QBBsA1BtQFBBxAAAAsgARAQIAEjBEEDEAoLIAALgAIBBX9B4AgQAUHQChABQcAMEAFB8NUAEAFB4NcAEAFB4NYAEAFB8AwQAUHQ2QAQAUGw2gAQASMEIgEQAyEAA0AgACABRwRAIAAQBxogAEEUahAcIAAQAyEADAELCyMCRSMFIgMQAyEAA0AgACADRwRAIAAQBxogAEEUahAcIAAQAyEADAELCyMBIgQQAyEAA0AgACAERwRAIAAQBxogABADIABBpNsASQRAIABBADYCBCAAQQA2AggFIwMgABALayQDIABBBGoiAEGk2wBPBEAjAEUEQBANCyMAIAAQDhAZCwshAAwBCwsgBCAENgIEIAQgBDYCCCADJAEgBCQFJAILqAEBBX9BgAJBBxAGIgFBAEGAAvwLAANAIABBgAJIBEAgASAAIAAQBSAAQQFqIQAMAQsLQQAhAANAIABBgAJIBEAgASAAEAIgAmohBCAAQSBvIgJB7AgoAgBPBEBB8NUAQbDWAEHyAEEqEAAACyABIAAQAiEDIAEgACABIAQgAkHkCCgCAGotAABqQf8BcSICEAIQBSABIAIgAxAFIABBAWohAAwBCwsgAQuFBAEGfyABECEhAQNAIAJB3AooAgBIBEACQAJ/QQFB0AogAhAeIgUgAUYNABpBACAFRSABRXINABpBACAFEAQgARAEIgZHDQAaIAFBACAFIAYQEkULBEBBASEDDAELIAJBAWohAgwCCwsLIANFBEBBACECA0AgAkHMDCgCAEgEQAJAQcAMIAIQHiEFIAEQBCAF")
        append("EARKBH9B/v///wEgARAEIgYgBkH+////AUobIAUQBCIGayIHQQBIBH9BAQUgASAHIAUgBhASCwVBAQtFBEBBASEDDAELIAJBAWohAgwCCwsLCyADRQRAQQAQEw8LECYhAkEAIQNBACEBA0AgAUGAEEgEQCACIARBAWpB/wFxIgQQAiADakH/AXEhAyACIAQQAiEFIAIgBCACIAMQAhAFIAIgAyAFEAUgAUEBaiEBDAELCyAAKAIIIgUQEyEGQQAhAQNAIAEgBUgEQCACIARBAWpB/wFxIgQQAiADakH/AXEhAyACIAQQAiEHIAIgBCACIAMQAhAFIAIgAyAHEAUgASAAKAIITwRAQfDVAEGQ2QBBpwFBLRAAAAsgAiACIAQQAiACIAMQAmpB/wFxEAIgASAAKAIEai0AAHNB/wFxIQcgASAGKAIITwRAQfDVAEGQ2QBBsgFBLRAAAAsgASAGKAIEaiAHOgAAIAFBAWohAQwBCwsgBgsLgT6pAQBBjAgLATwAQZgICygBAAAAIAAAAOT5sn2MGm71A325isVOIfC51sOngf5CrWXA6bc/FIotAEHMCAsBLABB2AgLFQQAAAAQAAAAIAQAACAEAAAgAAAAIABB/AgLATwAQYgJCykCAAAAIgAAAHAAbABhAHkAZQByAC4AdgBpAGQAegBlAGUALgB3AHQAZgBBvAkLASwAQcgJCxkCAAAAEgAAAGwAbwBjAGEAbABoAG8AcwB0AEHsCQsBLABB+AkLGQIAAAASAAAAMQAyADcALgAwAC4AMAAuADEAQZwKCwEcAEGoCgsSAQAAAAwAAACQBAAA0AQAAAAFAEG8CgsBLABByAoLFQUAAAAQAAAAMAUAADAFAAAMAAAAAwBB7AoLASwAQfgKCx8CAAAAGAAAAC4AbABvAHYAYQBiAGwAZQAuAGEAcABwAEGcCwsBPABBqAsLLQIAAAAmAAAALgBsAG8AdgBhAGIAbABlAHAAcgBvAGoA")
        append("ZQBjAHQALgBjAG8AbQBB3AsLASwAQegLCx0CAAAAFgAAAC4AdgBpAGQAegBlAGUALgB3AHQAZgBBjAwLARwAQZgMCxIBAAAADAAAAIAFAACwBQAA8AUAQawMCwEsAEG4DAsVBQAAABAAAAAgBgAAIAYAAAwAAAADAEHcDAsBPABB6AwLLwIAAAAoAAAAQQBsAGwAbwBjAGEAdABpAG8AbgAgAHQAbwBvACAAbABhAHIAZwBlAEGcDQsBPABBqA0LJQIAAAAeAAAAfgBsAGkAYgAvAHIAdAAvAHQAYwBtAHMALgB0AHMAQdwNCwE8AEHoDQslAgAAAB4AAAB+AGwAaQBiAC8AcgB0AC8AdABsAHMAZgAuAHQAcwBBtA4LgAQSEBMUFRYXGBkaGxwdHh8gIRAQIhAQECMkJSYnKCkQKisQEBAQEBAQEBAQECwtLhAvEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQMBAQEDEQMjM0NTY3EBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEDgQEDk6EDs8PRAQEBAQED4QED9AQUJDREVGR0hJSktMEE1OTxAQEBAQEBAQEBAQEBAQEBAQEBAQEFAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEFFSEBAQUxAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBBUEBAQEBAQEBAQEBAQEBAQEBAQ")
        append("EBBVVhAQEBAQEBBXEBAQEBBYWVoQEBAQEFtcEBAQEBAQEBAQXRAQEBAQEBAQEBAQEABB1BILOP//////////////////////////////////////////AAAAAIBAAAQAAABAAQAAAAAAAAAAoZABAEGqEwsb////////////////////////////////MASwAEHkEwsC+AMAQf8TCySCAAAAAAAA/v////+/tgAAAAAAEAA/AP8XAAAAAAH4//8AAAEAQa4UCxDAv/89AAAAgAIAAAD///8HAEHIFAsYwP8BAAAAAAAA+D8kAADA//8/AAAAAAAOAEHuFAuhAfj//////wcAAAAAAAAU/iH+AAwAAgACAAAAAAAAEB4gAAAMAABABgAAAAAAABCGOQIAAAAjAAYAAAAAAAAQviEAAAwAAPwCAAAAAAAAkB4gYAAMAAAABAAAAAAAAAABIAAAAAAAABEAAAAAAADAwT1gAAwAAAACAAAAAAAAkEAwAAAMAAAAAwAAAAAAABgeIAAADAAAAAIAAAAAAAAAAARcAEGaFgsE8gfAfwBBqhYLBPIfQD8AQbcWCxYDAACgAgAAAAAAAP5/3+D//v///x9AAEHZFgsP4P1mAAAAwwEAHgBkIAAgAEHzFgsBEABB/xYLAeAAQZYXCzQcAAAAHAAAAAwAAAAMAAAAAAAAALA/QP6PIAAAAAAAeAAAAAAAAAgAAAAAAAAAYAAAAAACAEHYFwsEhwEEDgBB9hcLToAJAAAAAAAAQH/lH/ifAAAAAIAA//8BAAAAAAAAAA8AAAAAANAXBAAAAAD4DwADAAAAPDsAAAAAAABAowMAAAAAAADwzwAAAAAAAAAAPwBBzhgLJvf//SEQAwAAAAAA8P////////8HAAEAAAD4///////////////7AEGLGQsooAPgAOAA4ABgAPgAA5B8AAAAAAAA3/8CgAAA/x8AAAAAAAD/////AQBBwxkLATAAQdEZ")
        append("CwKAAwBB4RkLA4AAgABB8BkLCv////8AAAAAAIAAQZQaCwggAAAAADw+CABBpxoLAX4AQbMaCwRwAAAgAEHzGgsDPwAQAEGBGwsHgPe/AAAA8ABBkhsLBwMA/////wMAQaIbCwQBAAAHAEGzGwsHA0QIAABgEABBzBsLRzAAAAD//wOAAAAAAMA/AACA/wMAAAAAAAcAAAAAAMgzAIAAAGAAAAAAAAAAAH5mAAgQAAAAAAEQAAAAAAAAncECAAAgADBYAEGfHAsD+AAOAEGwHAsIICEAAAAAAEAAQcocCxX8/wMAAAAAAAAA//8IAP//AAAAACQAQfMcCyGAgEAABAAAAEABAAAAAAABAAAAAMAAAAAAAAAAAAgAAA4AQbMdCwEgAEHQHQsBAQBB4h0LAsAHAEH0HQsIbvAAAAAAAIcAQZAeCwlgAAAAAAAAAPAAQckeCwEYAEHcHgsDwP8BAEH0Hgs6AgAAAAAAAP9/AAAAAAAAgAMAAAAAAHgmACAAAAAAAAAHAAAAgO8fAAAAAAAAAAgAAwAAAAAAwH8AngBBuR8LA4DTQABBzx8LFID4BwAAAwAAAAAAABgBAAAAwB8fAEH7HwsF/1wAAEAAQYogCwP4hQ0AQaogCwY8sAEAADAAQbogCwP4pwEAQckgCwIovwBB1yALA+C8DwBB+SALA4D/BgBBmyELAlgIAEGuIQsa8AwBAAAA/gcAAAAA+HmAAH4OAAAAAAD8fwMAQdohCwJ/vwBB5iELBfz///xtAEH6IQsDfrS/AEGGIgsBowBBsiILChgAAAAAAAAA/wEAQfIiCwsfAAAAAAAAAH8ADwBBnSMLFIAAAAAAAAAAgP//AAAAAAAAAAAbAEHHIwsCYA8AQeAjCwqAA/j/5w8AAAA8AEH8IwsBHABBlCQLFv///////3/4//////8fIAAQAAD4/v8AQbQkCwZ////52wcAQdokCwL/PwBBkSULAfAAQa4lCwF/AEG8JQsC")
        append("8A8AQfMlCwH4AEH0JQuABBITFBUWFxAQEBAQEBAQEBAYEBAZEBAQEBAQEBAaGxEcHR4QEB8QEBAQEBAQICEQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAiIxAQECQQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQJRAQECYQEBAQJxAQEBAQEBAoEBAQEBAQEBAQEBApEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQECoQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQECssLS4QEBAQEBAQEBAQEBAQEBAQEC8QEBAQEBAQMBAQEBAQEBAQEBAQEBAQAEGUKgt9//////////////////////////////////////////8AAAAAAAAAAP7//wf+//8HAAAAAAAEIAT//3////9/////////////////////////////////9/D/////////////////////////////////7/////8BAwAAAB8AQZwrC0ogAAAAAADPvEDX///7////////////v///////////////////////A/z///////////////////////////7///9/AP//////AQBBiCwLDP////+/")
        append("IP//////5wBBqCwLDP////////////8/PwBBxCwLUP8B///////nAAAAAAAAAAD///////////////////////////////8AAAAAAAAAAP//Pz//////Pz//qv///z/////////fX9wfzw//H9wfAEGiLQsGAoAAAP8fAEG0LQsRhPwvPlC9H/LgQwAA/////xgAQeotCzDA////////AwAA//////9///////9//////////////////////x94DAD/////vyAAQbwuCwz//////z8AAP///z8AQdguCz/8////////////////eP////////wHAAAAAGAHAAAAAAAA///////3/wH/////////////AAAAAAAAAAB/APgAQbgvCwj+//8H/v//BwBB1C8LCv////////////8AQeovCwr/////D/////8PAEGEMAsP////////BwD///////8HAEGoMAsI//////////8AQbwwCwj//////////wBB1DALiQH/////////////3///////////32Te/+vv/////////7/n39////97X/z9//////////////////////////////////////////////////////8//////f//9/////f//9/////f//9/////f/////3////9///3DwAAAAAAAP//////////DwBB+jELDP///wP///8D////AwBBlDILgAQHCAkKCwwGBgYGBgYGBgYGDQYGDgYGBgYGBgYGDxAREgYTBgYGBgYGBgYGBhQVBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGFhcGBgYYBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYG")
        append("BgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYZBgYGBhoGBgYGBgYGGwYGBgYGBgYGBgYGHAYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYdBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYeBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgBBgzcLFCQrKysrKysrKwEAVFZWVlZWVlZWAEGqNwufAxgAAAArKysrKysrBysrW1ZWVlZWVlZKVlYFMVAxUDFQMVAxUDFQMVAxUCRQeTFQMVAxOFAxUDFQMVAxUDFQMVAxUE4xAk4NDU4DTgAkbgBOMSZuUU4kUE45FIEbHR1TMVAxUA0xUDFQMVAbUyRQMQJce1x7XHtce1x7FHlce1x7XC0rSQNIA3hcexQAlgoBKygGBgAqBioqKwe7tSseACsHKysrASsrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrASsrKysrKysrKysrKysrKysrKysrKysrKisrKysrKysrKysrKyvNRs0rACUrBwEGAVVWVlZWVlVWVgIkgYGBgYEVgYGBAAArALLRstGy0bLRAADNzAEA19fX19eDgYGBgYGBgYGBgaysrKysrKysrKwcAAAAAAAxUDFQMVAxUDFQMQIAADFQMVAxUDFQMVAxUDFQMVAxUE4xUDFQTjFQMVAxUDFQMVAxUDFQMQKHpoemh6aHpoemh6aHpoemKisrKysrKysrKysrKwAAAFRW")
        append("VlZWVlZWVlZWVlYAQac7CyFUVlZWVlZWVlZWVlZWDAAMKisrKysrKysrKysrKysHKgEAQf07C3cqKysrKysrKysrKysrKysrKysrKysrKysrKytWVmyBFQArKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysHbANBKytWVlZWVlZWVlZWVlZWVixWKysrKysrKysrKysrKysrKysrKysrAQBBnD0LCAxsAAAAAAAGAEHKPQvoAgYlBiUGJQYlBiUGJQYlBiUGJQYlBiUGJQYlBiUGJQYlBiUGJQYlBiUGJQYlBiUGJQYlVnqeJgYlBiUGJQYlBiUGJQYlBiUGJQYlBiUGJQYlBiUGJQYBKytPVlYsK39WVjkrK1VWVisrT1ZWLCt/VlaBN3Vbe1wrK09WVgKsBAAAOSsrVVZWKytPVlYsKytWVjITgVcAb4F+ydd+LYGBDn45f29XAIGBfhUAfgMrKysrKysrKysrKysHKyQrlysrKysrKysrKyorKysrK1ZWVlZWgIGBgYE5uyorKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrAYGBgYGBgYGBgYGBgYGBgcmsrKysrKysrKysrKysrKzQDQBOMQK0wcHX1yRQMVAxUDFQMVAxUDFQMVAxUDFQMVAxUDFQMVAxUDFQMVDX11PBR9TX19cFKysrKysrKysrKysrBwEAAQBBjcEACx9OMVAxUDFQMVAxUDFQMVANAAAAAAAkUDFQMVAxUDFQAEHOwQALVisrKysrKysrKysreVx7XHtPe1x7XHtce1x7XHtce1x7XHtce1wtKyt5FFx7XC15KlwnXHtce1x7pAAKtFx7XHtPA3g4KysrKysrKysrKysrK08tKysBAEG/wgALAUgAQcnCAAsbKisrKysrKysrKysrKysrKysrKysrKysrKysrAEGFwwALFCsrKysrKysrBwBIVlZW")
        append("VlZWVlYCAEHQwwALGysrKysrKysrKysrKytVVlZWVlZWVlZWVlZWDgBBisQACxokKysrKysrKysrKysHAFZWVlZWVlZWVlZWVgBB0MQACyckKysrKysrKysrKysrKysrKwcAAAAAVlZWVlZWVlZWVlZWVlZWVlYAQbHFAAsWKisrKysrKysrKytWVlZWVlZWVlZWDgBB58UACxYqKysrKysrKysrK1ZWVlZWVlZWVlYOAEGoxgALFysrKysrKysrKysrVVZWVlZWVlZWVlYOAEGBxwALCAgAAFYBAAA5AEGQxwALvAcBIAAAAOD//wC/HQAA5wIAAHkAAAIkAAABAQAAAP///wAAAAABAgAAAP7//wE5//8AGP//AYf//wDU/v8AwwAAAdIAAAHOAAABzQAAAU8AAAHKAAABywAAAc8AAABhAAAB0wAAAdEAAACjAAAB1QAAAIIAAAHWAAAB2gAAAdkAAAHbAAAAOAAAAwAAAACx//8Bn///Acj//wIoJAAAAAAAAQEAAAD///8AM///ACb//wF+//8BKyoAAV3//wEoKgAAPyoAAT3//wFFAAABRwAAAB8qAAAcKgAAHioAAC7//wAy//8ANv//ADX//wBPpQAAS6UAADH//wAopQAARKUAAC///wAt//8A9ykAAEGlAAD9KQAAK///ACr//wDnKQAAQ6UAACqlAAC7//8AJ///ALn//wAl//8AFaUAABKlAAIkTAAAAAAAASAAAADg//8BAQAAAP///wBUAAABdAAAASYAAAElAAABQAAAAT8AAADa//8A2///AOH//wDA//8Awf//AQgAAADC//8Ax///ANH//wDK//8A+P//AKr//wCw//8ABwAAAIz//wHE//8AoP//Afn//wIacAABAQAAAP///wEgAAAA4P//AVAAAAEPAAAA8f//AAAAAAEwAAAA0P//AQEAAAD///8AAAAAAMALAAFgHAAAAAAAAdCXAAEIAAAA+P//")
        append("AgWKAAAAAAABQPT/AJ7n/wDCiQAA2+f/AJLn/wCT5/8AnOf/AJ3n/wCk5/8AAAAAADiKAAAEigAA5g4AAQEAAAD///8AAAAAAMX//wFB4v8CHY8AAAgAAAH4//8AAAAAAFYAAAGq//8ASgAAAGQAAACAAAAAcAAAAH4AAAAJAAABtv//Aff//wDb4/8BnP//AZD//wGA//8Bgv//AgWsAAAAAAABEAAAAPD//wEcAAABAQAAAaPi/wFB3/8But//AOT//wILsQABAQAAAP///wEwAAAA0P//AAAAAAEJ1v8BGvH/ARnW/wDV1f8A2NX/AeTV/wED1v8B4dX/AeLV/wHB1f8AAAAAAKDj/wAAAAABAQAAAP///wIMvAAAAAAAAQEAAAD///8BvFr/AaADAAH8df8B2Fr/ADAAAAGxWv8BtVr/Ab9a/wHuWv8B1lr/Aeta/wHQ//8BvVr/Ach1/wAAAAAAMGj/AGD8/wAAAAABIAAAAOD//wAAAAABKAAAANj//wAAAAABQAAAAMD//wAAAAABIAAAAOD//wAAAAABIAAAAOD//wAAAAABIgAAAN7//wBBzc4ACwUGJ1FvdwBB3M4ACxJ8AAB/AAAAAAAAAACDjpKXAKoAQfjOAAsCtMQAQfLPAAsGxskAAADbAEHL0AALDt4AAAAA4QAAAAAAAADkAEHk0AALAecAQbrRAAsB6gBBtdIACwHtAEHM0gALkAMwDDENeA5/D4AQgRGGEokTihOOFI8VkBaTE5QXlRiWGZcamhucGZ0cnh2fHqYfqR+uH7EgsiC3Ib8ixSPII8sj3STyI/Yl9yYgLTouPS8+MD8xQDFDMkQzRTRQNVE2UjdTOFQ5WTpbO1w8YT1jPmU/ZkBoQWlCakBrQ2xEb0JxRXJGdUd9SIJJh0qJS4pMi0yMTZJOnU+eUEVXex18HX0df1iGWYhaiVqKWoxbjlyPXKxdrV6uXq9ewl/MYM1hzmHPYtBj0WTVZdZm")
        append("12fwaPFp8mrza/Rs9W35bv0t/i3/LVBpUWlSaVNpVGlVaVZpV2lYaVlpWmlbaVxpXWleaV9pggCDAIQAhQCGAIcAiACJAMB1z3aAiYGKgouFjIaNcJ1xnXaed554n3mfeqB7oHyhfaGzorqju6O8pL6lw6LMpNqm26blauqn66fsbvOi+Kj5qPqp+6n8pCawKrErsk6zhAhiumO7ZLxlvWa+bb9uwG/BcMJ+w3/Dfc+N0JTRq9Ks063UsNWx1rLXxNjF2cbaAEHc1QALATwAQejVAAsrAgAAACQAAABJAG4AZABlAHgAIABvAHUAdAAgAG8AZgAgAHIAYQBuAGcAZQBBnNYACwEsAEGo1gALIQIAAAAaAAAAfgBsAGkAYgAvAGEAcgByAGEAeQAuAHQAcwBBzNYACwF8AEHY1gALZQIAAABeAAAARQBsAGUAbQBlAG4AdAAgAHQAeQBwAGUAIABtAHUAcwB0ACAAYgBlACAAbgB1AGwAbABhAGIAbABlACAAaQBmACAAYQByAHIAYQB5ACAAaQBzACAAaABvAGwAZQB5AEHM1wALASwAQdjXAAsjAgAAABwAAABJAG4AdgBhAGwAaQBkACAAbABlAG4AZwB0AGgAQfzXAAsBPABBiNgACy0CAAAAJgAAAH4AbABpAGIALwBhAHIAcgBhAHkAYgB1AGYAZgBlAHIALgB0AHMAQbzYAAsBPABByNgACy0CAAAAJgAAAH4AbABpAGIALwBzAHQAYQB0AGkAYwBhAHIAcgBhAHkALgB0AHMAQfzYAAsBPABBiNkACysCAAAAJAAAAH4AbABpAGIALwB0AHkAcABlAGQAYQByAHIAYQB5AC4AdABzAEG82QALATwAQcjZAAsxAgAAACoAAABPAGIAagBlAGMAdAAgAGEAbAByAGUAYQBkAHkAIABwAGkAbgBuAGUAZABBnNoACwE8AEGo2gALLwIAAAAoAAAATwBiAGoAZQBjAHQAIABp")
        append("AHMAIABuAG8AdAAgAHAAaQBuAG4AZQBkAEGA2wALIQgAAAAgAAAAIAAAACAAAAAAAAAAQgAAAAJBAABBAAAAZA==")
    }


    /* ---------------------------------------------------------------------- */
    /* 1. MakimaDL Direct Downloads & CDN Stream Decryption                  */
    /* ---------------------------------------------------------------------- */

    data class MakimaDLExports(
        val alloc: String = "_TH0g",
        val reset: String = "_Tk4p",
        val decryptDownload: String = "_pSkr"
    )

    @Volatile
    private var makimaDLModule: WasmModule? = null

    @Volatile
    private var makimaDLExports: MakimaDLExports = MakimaDLExports()

    @Volatile
    private var makimaDLModuleHash: String? = null

    private fun getOrLoadMakimaDLModule(client: OkHttpClient): Pair<WasmModule, MakimaDLExports> {
        makimaDLModule?.let { return it to makimaDLExports }
        synchronized(this) {
            makimaDLModule?.let { return it to makimaDLExports }

            var loadedModule: WasmModule? = null
            var exports = MakimaDLExports()

            // 1. Try dynamic manifest from https://www.1shows.org/makimaDL-manifest.json
            val candidateSites = listOf("https://www.1shows.org", "https://www.1shows.bz")
            for (site in candidateSites) {
                try {
                    val mReq = Request.Builder()
                        .url("$site/makimaDL-manifest.json")
                        .header("User-Agent", USER_AGENT)
                        .header("Referer", "$site/")
                        .header("Origin", site)
                        .build()
                    val mResp = client.newCall(mReq).execute()
                    if (mResp.isSuccessful) {
                        val mBody = mResp.body?.string().orEmpty()
                        val mObj = json.parseToJsonElement(mBody).jsonObject
                        val relWasmUrl = mObj["url"]?.jsonPrimitive?.contentOrNull ?: ""
                        val expObj = mObj["exports"]?.jsonObject
                        val allocName = expObj?.get("alloc")?.jsonPrimitive?.contentOrNull ?: "_TH0g"
                        val resetName = expObj?.get("reset")?.jsonPrimitive?.contentOrNull ?: "_Tk4p"
                        val decName = expObj?.get("decryptDownload")?.jsonPrimitive?.contentOrNull ?: "_pSkr"

                        if (relWasmUrl.isNotBlank()) {
                            val wasmUrl = if (relWasmUrl.startsWith("http")) relWasmUrl else "$site$relWasmUrl"
                            val wReq = Request.Builder()
                                .url(wasmUrl)
                                .header("User-Agent", USER_AGENT)
                                .header("Referer", "$site/")
                                .header("Origin", site)
                                .build()
                            val wResp = client.newCall(wReq).execute()
                            if (wResp.isSuccessful) {
                                val wBytes = wResp.body?.bytes()
                                if (wBytes != null && wBytes.isNotEmpty()) {
                                    loadedModule = Parser.parse(ByteArrayInputStream(wBytes))
                                    exports = MakimaDLExports(allocName, resetName, decName)
                                    makimaDLModuleHash = mObj["hash"]?.jsonPrimitive?.contentOrNull
                                    safeLog("OneShowsWasmEngine", "Loaded live MakimaDL wasm from $wasmUrl (${wBytes.size} bytes)")
                                    break
                                }
                            }
                        }
                    }
                } catch (ce: CancellationException) {
                    throw ce
                } catch (t: Throwable) {
                    safeLog("OneShowsWasmEngine", "Manifest fetch failed on $site: ${t.message}", t)
                }
            }

            // 2. Classpath resource fallback
            if (loadedModule == null) {
                try {
                    val res = OneShowsWasmEngine::class.java.classLoader?.getResourceAsStream("makimaDL.wasm")
                    if (res != null) {
                        val bytes = res.use { it.readBytes() }
                        loadedModule = Parser.parse(ByteArrayInputStream(bytes))
                        exports = MakimaDLExports("_TH0g", "_Tk4p", "_pSkr")
                    }
                } catch (ce: CancellationException) {
                    throw ce
                } catch (t: Throwable) {
                    safeLog("OneShowsWasmEngine", "Classpath makimaDL.wasm fallback error: ${t.message}", t)
                }
            }

            // 3. Embedded Base64 fallback (guarantees 100% runtime success)
            if (loadedModule == null) {
                try {
                    val bytes = Base64.getDecoder().decode(MAKIMA_DL_B64)
                    loadedModule = Parser.parse(ByteArrayInputStream(bytes))
                    exports = MakimaDLExports("_TH0g", "_Tk4p", "_pSkr")
                } catch (ce: CancellationException) {
                    throw ce
                } catch (t: Throwable) {
                    safeLog("OneShowsWasmEngine", "Embedded makimaDL fallback error: ${t.message}", t)
                    throw IllegalStateException("Failed to load makimaDL wasm module", t)
                }
            }

            val finalMod = loadedModule ?: throw IllegalStateException("Null makimaDL wasm module")
            makimaDLModule = finalMod
            makimaDLExports = exports
            return finalMod to exports
        }
    }

    suspend fun decryptPayload(
        client: OkHttpClient,
        tokenHex: String,
        ivHex: String,
        tagHex: String,
        ctHex: String
    ): String? = decryptMakimaDLPayload(client, tokenHex, ivHex, tagHex, ctHex)

    suspend fun decryptMakimaDLPayload(
        client: OkHttpClient,
        tokenHex: String,
        ivHex: String,
        tagHex: String,
        ctHex: String
    ): String? = withContext(Dispatchers.IO) {
        try {
            val (module, exports) = getOrLoadMakimaDLModule(client)

            val abortFn = HostFunction(
                "env",
                "abort",
                listOf(ValueType.I32, ValueType.I32, ValueType.I32, ValueType.I32),
                emptyList()
            ) { _, _ -> longArrayOf() }

            val importValues = ImportValues.builder()
                .withFunctions(listOf(abortFn))
                .build()

            val instance = Instance.builder(module)
                .withImportValues(importValues)
                .build()

            val alloc = instance.export(exports.alloc)
            val reset = instance.export(exports.reset)
            val decrypt = instance.export(exports.decryptDownload)
            val memory = instance.memory()

            fun writeBytes(bytes: ByteArray): Pair<Int, Int> {
                val ptr = alloc.apply(bytes.size.toLong())[0].toInt()
                memory.write(ptr, bytes)
                return ptr to bytes.size
            }

            val tokenBytes = hexToBytes(tokenHex)
            val ivBytes = hexToBytes(ivHex)
            val tagBytes = hexToBytes(tagHex)
            val ctBytes = hexToBytes(ctHex)

            val f = writeBytes(tokenBytes)
            val p = writeBytes(ivBytes)
            val m = writeBytes(ctBytes)
            val x = writeBytes(tagBytes)

            val outBufPtr = alloc.apply(ctBytes.size.toLong())[0].toInt()

            val resLen = decrypt.apply(
                f.first.toLong(), f.second.toLong(),
                p.first.toLong(), p.second.toLong(),
                m.first.toLong(), m.second.toLong(),
                x.first.toLong(), x.second.toLong(),
                outBufPtr.toLong()
            )[0].toInt()

            if (resLen <= 0) {
                try { reset.apply() } catch (_: Throwable) {}
                safeLog("OneShowsWasmEngine", "decryptMakimaDLPayload return code <= 0: $resLen")
                return@withContext null
            }

            val decryptedBytes = memory.readBytes(outBufPtr, resLen)
            try { reset.apply() } catch (_: Throwable) {}

            String(decryptedBytes, Charsets.UTF_8)
        } catch (ce: CancellationException) {
            throw ce
        } catch (t: Throwable) {
            safeLog("OneShowsWasmEngine", "decryptMakimaDLPayload exception: ${t.message}", t)
            null
        }
    }

    /* ---------------------------------------------------------------------- */
    /* 2. Vidrock AES-256-GCM Native Stream Decryption                        */
    /* ---------------------------------------------------------------------- */

    private const val VIDROCK_KEY_HEX = "7f3e9c2a8b5d1f4e6a9c3b7d2e5f8a1c4b6d9e2f5a8c1b4d7e9f2a5c8b1d4e7f"

    fun decryptVidrockPayload(ciphertextB64Url: String): String? {
        return try {
            val clean = ciphertextB64Url.trim().replace('-', '+').replace('_', '/')
            val padded = clean.padEnd(4 * ((clean.length + 3) / 4), '=')
            val raw = Base64.getDecoder().decode(padded)
            if (raw.size <= 28) return null // 12-byte IV + 16-byte tag minimum

            val iv = raw.copyOfRange(0, 12)
            val cipherWithTag = raw.copyOfRange(12, raw.size)

            val keyBytes = hexToBytes(VIDROCK_KEY_HEX)
            val keySpec = SecretKeySpec(keyBytes, "AES")
            val gcmSpec = GCMParameterSpec(128, iv)
            val cipher = Cipher.getInstance("AES/GCM/NoPadding")
            cipher.init(Cipher.DECRYPT_MODE, keySpec, gcmSpec)

            val decryptedBytes = cipher.doFinal(cipherWithTag)
            String(decryptedBytes, Charsets.UTF_8)
        } catch (t: Throwable) {
            safeLog("OneShowsWasmEngine", "decryptVidrockPayload error: ${t.message}", t)
            null
        }
    }

    /* ---------------------------------------------------------------------- */
    /* 3. Vidy (wecollege) PRNG Stream Cipher Decryption                     */
    /* ---------------------------------------------------------------------- */

    private val VIDY_U = byteArrayOf(109, 118, 109, 49) // "mvm1"

    private fun vidyM(value: Int): Int {
        var e = value
        e = e xor (e ushr 16)
        e = (e.toLong() * 2246822507L).toInt()
        e = e xor (e ushr 13)
        e = (e.toLong() * 3266489909L).toInt()
        e = e xor (e ushr 16)
        return e
    }

    private fun vidyP(e: Int, t: Int): Int {
        return Integer.rotateLeft(e, t and 31)
    }

    fun decryptVidyPayload(ciphertextB64: String, seed: String, mediaIdStr: String): String? {
        return try {
            val clean = ciphertextB64.trim().replace('-', '+').replace('_', '/')
            val padded = clean.padEnd(4 * ((clean.length + 3) / 4), '=')
            val o = Base64.getDecoder().decode(padded)
            if (o.size < VIDY_U.size) return null

            val mediaIdNum = mediaIdStr.toLongOrNull()?.toInt() ?: 0
            var t1 = 2166136261L.toInt()
            for (i in seed.indices) {
                val code = seed[i].code
                t1 = ((t1 xor code).toLong() * 16777619L).toInt()
            }
            val t2 = vidyM(mediaIdNum xor 2654435769L.toInt())
            var s = vidyM(vidyM(t1) xor t2)

            val a = IntArray(61)
            val setIndices = BooleanArray(61)
            for (e in 0 until 8) {
                val t = ((s.toLong() and 0xFFFFFFFFL) % 61).toInt()
                s = vidyP((s.toLong() + 2654435769L).toInt(), 7 + (7 and e))
                a[t] = s xor vidyM(s)
                setIndices[t] = true
                s = vidyM(s + t)
            }

            var acc = vidyM(2779096485L.toInt() xor s)

            val n = ByteArray(o.size)
            var step = 0
            var byteIdx = 0
            while (byteIdx < o.size) {
                val d = ((acc.toLong() and 0xFFFFFFFFL) % 61).toInt()
                val r = if (setIndices[d]) -1 else 0
                val iVal = a[d]

                val term = iVal xor ((2654435769L * (step + 1)).toInt())
                val lVal = (acc xor term) or (acc and term and r)

                val rot1 = vidyP(lVal + acc, 31 and d)
                val rot2 = vidyP(acc, 31 and (d * 7))
                val newAcc = vidyM((rot1 xor rot2) + 2654435769L.toInt())

                a[d] = newAcc
                setIndices[d] = true
                acc = newAcc
                val tGen = newAcc

                step++

                n[byteIdx++] = (tGen and 0xFF).toByte()
                if (byteIdx < o.size) n[byteIdx++] = ((tGen ushr 8) and 0xFF).toByte()
                if (byteIdx < o.size) n[byteIdx++] = ((tGen ushr 16) and 0xFF).toByte()
                if (byteIdx < o.size) n[byteIdx++] = ((tGen ushr 24) and 0xFF).toByte()
            }

            for (i in o.indices) {
                o[i] = (o[i].toInt() xor n[i].toInt()).toByte()
            }

            for (i in VIDY_U.indices) {
                if (o[i] != VIDY_U[i]) {
                    return null
                }
            }

            String(o, VIDY_U.size, o.size - VIDY_U.size, Charsets.UTF_8)
        } catch (t: Throwable) {
            safeLog("OneShowsWasmEngine", "decryptVidyPayload error: ${t.message}", t)
            null
        }
    }

    /* ---------------------------------------------------------------------- */
    /* 4. Vidzee WASM Decryption                                              */
    /* ---------------------------------------------------------------------- */

    @Volatile
    private var vidzeeModule: WasmModule? = null

    private fun getOrLoadVidzeeModule(client: OkHttpClient): WasmModule {
        vidzeeModule?.let { return it }
        synchronized(this) {
            vidzeeModule?.let { return it }

            var module: WasmModule? = null
            try {
                val resourceStream = OneShowsWasmEngine::class.java.classLoader?.getResourceAsStream("vidzee.wasm")
                if (resourceStream != null) {
                    val bytes = resourceStream.use { it.readBytes() }
                    module = Parser.parse(ByteArrayInputStream(bytes))
                }
            } catch (_: Throwable) {}

            if (module == null) {
                try {
                    val bytes = Base64.getDecoder().decode(VIDZEE_B64)
                    module = Parser.parse(ByteArrayInputStream(bytes))
                } catch (t: Throwable) {
                    safeLog("OneShowsWasmEngine", "Failed to load vidzee wasm module: ${t.message}", t)
                    throw IllegalStateException("Failed to load vidzee wasm module", t)
                }
            }

            val finalMod = module ?: throw IllegalStateException("Null vidzee module")
            vidzeeModule = finalMod
            return finalMod
        }
    }

    suspend fun decryptVidzeePayload(
        client: OkHttpClient,
        cBase64: String,
        hostname: String = "player.vidzee.wtf"
    ): String? = withContext(Dispatchers.IO) {
        try {
            val module = getOrLoadVidzeeModule(client)

            val abortFn = HostFunction(
                "env",
                "abort",
                listOf(ValueType.I32, ValueType.I32, ValueType.I32, ValueType.I32),
                emptyList()
            ) { _, _ -> longArrayOf() }

            val importValues = ImportValues.builder()
                .withFunctions(listOf(abortFn))
                .build()

            val instance = Instance.builder(module)
                .withImportValues(importValues)
                .build()

            val allocNew = instance.export("__new")
            val pin = instance.export("__pin")
            val unpin = instance.export("__unpin")
            val decrypt = instance.export("decrypt")
            val memory = instance.memory()

            fun allocateString(s: String): Int {
                val byteLen = s.length * 2
                val ptr = allocNew.apply(byteLen.toLong(), 2L)[0].toInt()
                val buf = ByteBuffer.allocate(byteLen).order(ByteOrder.LITTLE_ENDIAN)
                for (ch in s) {
                    buf.putChar(ch)
                }
                memory.write(ptr, buf.array())
                return ptr
            }

            fun allocateByteArray(bytes: ByteArray): Int {
                val len = bytes.size
                val abPtr = pin.apply(allocNew.apply(len.toLong(), 1L)[0])[0].toInt()
                memory.write(abPtr, bytes)
                val dPtr = allocNew.apply(12L, 6L)[0].toInt()
                val buf = ByteBuffer.allocate(12).order(ByteOrder.LITTLE_ENDIAN)
                buf.putInt(abPtr)
                buf.putInt(abPtr)
                buf.putInt(len)
                memory.write(dPtr, buf.array())
                unpin.apply(abPtr.toLong())
                return dPtr
            }

            val rawBytes = Base64.getDecoder().decode(cBase64)
            val arrPtr = allocateByteArray(rawBytes)
            val hostPtr = allocateString(hostname)

            val resPtr = decrypt.apply(arrPtr.toLong(), hostPtr.toLong())[0].toInt()
            if (resPtr <= 0) return@withContext null

            val metaBytes = memory.readBytes(resPtr, 12)
            val metaBuf = ByteBuffer.wrap(metaBytes).order(ByteOrder.LITTLE_ENDIAN)
            metaBuf.int // skip bufPtr0
            val bufPtr = metaBuf.int
            val outLen = metaBuf.int

            if (outLen <= 0) return@withContext null

            val outBytes = memory.readBytes(bufPtr, outLen)
            String(outBytes, Charsets.UTF_8)
        } catch (ce: CancellationException) {
            throw ce
        } catch (t: Throwable) {
            safeLog("OneShowsWasmEngine", "decryptVidzeePayload error: ${t.message}", t)
            null
        }
    }

    /* ---------------------------------------------------------------------- */
    /* 5. Viduki Main & Altcha Decryption (Leon, Jill, Chris, Grace, etc.)    */
    /* ---------------------------------------------------------------------- */

    fun solveAltcha(salt: String, challenge: String, maxNumber: Long, algorithm: String = "SHA-256", signature: String = ""): String {
        val md = MessageDigest.getInstance(algorithm)
        var found = 0L
        for (n in 0L..maxNumber) {
            md.reset()
            val text = salt + n
            val digest = md.digest(text.toByteArray(Charsets.UTF_8))
            val hex = digest.joinToString("") { "%02x".format(it) }
            if (hex.equals(challenge, ignoreCase = true)) {
                found = n
                break
            }
        }
        val payload = """{"algorithm":"$algorithm","challenge":"$challenge","number":$found,"salt":"$salt","signature":"$signature","took":10}"""
        return Base64.getEncoder().encodeToString(payload.toByteArray(Charsets.UTF_8))
    }

    private val sessionNonceCache = ConcurrentHashMap<String, Pair<String, Long>>()

    suspend fun getVidukiSessionNonce(client: OkHttpClient, baseUrl: String): String? = withContext(Dispatchers.IO) {
        val cached = sessionNonceCache[baseUrl]
        if (cached != null && System.currentTimeMillis() - cached.second < 600_000L) {
            return@withContext cached.first
        }
        try {
            val chReq = Request.Builder()
                .url("$baseUrl/altcha-challenge")
                .header("Referer", "https://www.viduki.net/")
                .header("Origin", "https://www.viduki.net")
                .header("User-Agent", USER_AGENT)
                .build()
            val chBody = client.newCall(chReq).execute().use { it.body?.string().orEmpty() }
            if (chBody.isBlank()) return@withContext null

            val chObj = json.parseToJsonElement(chBody).jsonObject
            val salt = chObj["salt"]?.jsonPrimitive?.content ?: return@withContext null
            val target = chObj["challenge"]?.jsonPrimitive?.content ?: return@withContext null
            val maxNum = chObj["maxnumber"]?.jsonPrimitive?.content?.toLongOrNull() ?: 50000L
            val algo = chObj["algorithm"]?.jsonPrimitive?.content ?: "SHA-256"
            val sig = chObj["signature"]?.jsonPrimitive?.content ?: ""

            val altcha = solveAltcha(salt, target, maxNum, algo, sig)

            val bootReq = Request.Builder()
                .url("$baseUrl/bootstrap")
                .header("Referer", "https://www.viduki.net/")
                .header("Origin", "https://www.viduki.net")
                .header("User-Agent", USER_AGENT)
                .header("X-Altcha", altcha)
                .header("Accept", "application/json")
                .build()
            val bootBody = client.newCall(bootReq).execute().use { it.body?.string().orEmpty() }
            if (bootBody.isBlank()) return@withContext null

            val nonce = json.parseToJsonElement(bootBody).jsonObject["n"]?.jsonPrimitive?.content
            if (!nonce.isNullOrBlank()) {
                sessionNonceCache[baseUrl] = nonce to System.currentTimeMillis()
                nonce
            } else null
        } catch (ce: CancellationException) {
            throw ce
        } catch (t: Throwable) {
            safeLog("OneShowsWasmEngine", "getVidukiSessionNonce error: ${t.message}", t)
            null
        }
    }

    data class MakimaExports(
        val alloc: String = "_pRhU",
        val reset: String = "_twc7",
        val writeByte: String = "_sywi",
        val readByte: String = "_S02C",
        val decryptPepper: String = "_Uk9g",
        val decryptEnvelope: String = "_KejE",
        val dropPepper: String = "_9nwS"
    )

    data class VidukiServer(
        val name: String,
        val language: String,
        val useUpscale: Boolean = false,
        val useSpatialAudio: Boolean = false
    )

    private const val VIDUKI_WASM_B64 = "AGFzbQEAAAABZg1gAX8Bf2ACf38Bf2ADf39/AGACf38AYAAAYAF/AGAEf39/fwBgBX9/f39/AX9gA39/fgBgA39/fwF/YAABf2AKf39/f39/f39/fwF/YBV/f39/f39/f39/f39/f39/f39/f38BfwINAQNlbnYFYWJvcnQABgM4NwIBAAEEAAIFAQEAAQACAAMDAAUFAAcCAQABAAQIBAMDAgAFAwUBCQYDBAEKAQMCAAQCAAsBDAQFAwEAAQZKDn8BQcAIC38BQQALfwFBAAt/AUEAC38BQQALfwFBAAt/AUEAC38BQQALfwFBAAt/AUEAC38BQQALfwFBAAt/AUEAC38BQaygAgsHQggFX3BSaFUAMwVfdHdjNwAxBV9zeXdpADIFX1MwMkMANQVfVWs5ZwA0BV9LZWpFADYFXzlud1MANwZtZW1vcnkCAAgBKgwBNwrOWzdNACMNQQRrJA0QBSMNQQA2AgAjDSAANgIAIAEgACgCCE8EQEGgC0GgHkGyAUEtEAAACyMNIAA2AgAgACgCBCABaiACOgAAIw1BBGokDQtLACMNQQRrJA0QBSMNQQA2AgAjDSAANgIAIAEgACgCCE8EQEGgC0GgHkGnAUEtEAAACyMNIAA2AgAgACgCBCABai0AACMNQQRqJA0LJQAjDUEEayQNEAUjDUEANgIAIw0gADYCACAAKAIIIw1BBGokDQtDACMNQQRrJA0QBSMNQQA2AgAjDSAANgIAIAAQGSABTQRAQaALQaAfQc4AQSkQAAALIAAgAUECdGooAgAjDUEEaiQNCxoAIw1BrCBIBEBBwKACQfCgAkEBQQEQAAALCz4BAX8jDUEIayQNEAUjDUIANwMAIw1BDEEEEAwiATYCACMNIAE2AgQjDSABIAAQLSIANgIAIw1BCGokDSAAC0wAIw1BBGskDRAFIw1BADYCACMNIAA2AgAgABAZIAFNBEBBoAtBoB9B3QBBKRAAAAsjDSAANgIAIAAgAUECdGogAjYCACMNQQRqJA0LIwAgAEUEQA8LIABBFGsiABANIwhGBEAgABATIwRBAWokBAsLUQECfyMNQQhrJA0QBSMNQgA3AwAjDSABEAYiAzYCAANAIAEgAkoEQCMNIAM2AgQgAyACIAAgAmotAAAQASACQQFqIQIMAQsLIw1BCGokDSADC0sAIw1BBGskDRAFIw1BADYCACMNIAA2AgAgASAAKAIMTwRAQaALQdAdQfIAQSoQAAALIw0gADYCACAAKAIEIAFqLQAAIw1BBGokDQsKACAAKAIEQXxxC6MBAQF/IABB7P///wNPBEBB4AlBoApBhQJBHxAAAAsjASMCTwRAAkBBgBAhAgNAIAIQLGshAiMDRQRAIwFBAXRBgAhqJAIMAgsgAkEASg0ACyMBIwEjAmtBgAhJQQp0aiQCCwsjCkUEQBAcCyMKIABBEGoQKyICIAE2AgwgAiAANgIQIAIjCSMIECEgAhAiIwFqJAEgAkEUaiIBQQAgAPwLACABCwoAIAAoAgRBA3ELSAEBfyABRQRADwsgAUEUayIBEA0jCEYEQCAAQRRrIgAQDSIDIwhFRgRAIAAgASACGxATBSMDQQFGIANBA0ZxBEAgARATCwsLC0QAIw1BBGskDRAFIw1BADYCACAAQf////8ASwRAQfAIQaAfQTNBPBAAAAsjDSAAQQJ0QQkQDCIANgIAIw1BBGokDSAAC8MBAQR/IAEoAgBBfHEiA0GAAkkEfyADQQR2BUEfQfz///8DIAMgA0H8////A08bIgNnayIEQQdrIQIgAyAEQQRrdkEQcwshBCABKAIIIQUgASgCBCIDBEAgAyAFNgIICyAFBEAgBSADNgIECyABIAAgAkEEdCAEakECdGoiASgCYEYEQCABIAU2AmAgBUUEQCAAIAJBAnRqIgEoAgRBfiAEd3EhAyABIAM2AgQgA0UEQCAAIAAoAgBBfiACd3E2AgALCwsLvAIBBX8gASgCACEDIAFBBGogASgCAEF8cWoiBCgCACICQQFxBEAgACAEEBAgASADQQRqIAJBfHFqIgM2AgAgAUEEaiABKAIAQXxxaiIEKAIAIQILIANBAnEEQCABQQRrKAIAIgEoAgAhBiAAIAEQECABIAZBBGogA0F8cWoiAzYCAAsgBCACQQJyNgIAIARBBGsgATYCACAAIANBfHEiAkGAAkkEfyACQQR2BUEfQfz///8DIAIgAkH8////A08bIgJnayIDQQdrIQUgAiADQQRrdkEQcwsiAiAFQQR0akECdGooAmAhAyABQQA2AgQgASADNgIIIAMEQCADIAE2AgQLIAAgBUEEdCACakECdGogATYCYCAAIAAoAgBBASAFdHI2AgAgACAFQQJ0aiIAIAAoAgRBASACdHI2AgQLEgAgACAANgIEIAAgADYCCCAAC4YBAQJ/IAAjBkYEQCAAKAIIJAYLAkAgABALIgFFBEAgACgCCBoMAQsgASAAKAIIIgI2AgggAiABEB8LIwchASAAKAIMIgJBAk0Ef0EBBSACQYAgKAIASwRAQaALQeALQRVBHBAAAAsgAkECdEGEIGooAgBBIHELIQIgACABIwhFQQIgAhsQIQvSAQEDfwJAAkACQAJAAkACQAJAAkACQCAAQQhrKAIADgoAAQIDBAUICAgGBwsPCw8LDwsgABAjDwsgABAjDwsjDUEEayQNEAUjDUEANgIAIw0gADYCACAAKAIEIQEjDSAANgIAIAEgACgCDEECdGohAgNAIAEgAkkEQCABKAIAIgMEQCADEAgLIAFBBGohAQwBCwsjDSAANgIAIAAoAgAQCCMNQQRqJA0PCw8LAAsjDUEEayQNEAUjDUEANgIAIw0gADYCACAAKAIAEAgjDUEEaiQNC5UFAgZ/AX4jDUEUayQNEAUjDUEAQRT8CwAjDUEIEA8iATYCACMNIAE2AgQgAUEAQefMp9AGEAcjDSABNgIEIAFBAUGF3Z7bexAHIw0gATYCBCABQQJB8ua74wMQByMNIAE2AgQgAUEDQbrqv6p6EAcjDSABNgIEIAFBBEH/pLmIBRAHIw0gATYCBCABQQVBjNGV2HkQByMNIAE2AgQgAUEGQauzj/wBEAcjDSABNgIEIAFBB0GZmoPfBRAHIw0gADYCBCAAEAOsQgOGIQcjDSAANgIEIAAQA0HAAG9BOEgEfyMNIAA2AgRBwAAgABADQcAAb2sFIw0gADYCBEGAASAAEANBwABvawshBiMNIAA2AgQjDSAAEAMgBmoQBiIGNgIIA0AjDSAANgIEIAAQAyADSgRAIw0gBjYCBCMNIAA2AgwgBiADIAAgAxACEAEgA0EBaiEDDAELCyMNIAY2AgQjDSAANgIMIAYgABADQYABEAEDQCAEQQhIBEAjDSAGNgIEIw0gBjYCDCAGIAYQA0EBayAEayAHIARBA3SsiKdB/wFxEAEgBEEBaiEEDAELCwNAIw0gBjYCBCAGEAMgBUoEQCMNIAE2AgQjDSAGNgIMIAEgBiAFEC8gBUFAayEFDAELCyMNQSAQBiIANgIQA0AgAkEISARAIw0gADYCBCMNIAE2AgwgACACQQJ0IgMgASACEARBGHYQASMNIAA2AgQjDSABNgIMIAAgA0EBaiABIAIQBEEQdkH/AXEQASMNIAA2AgQjDSABNgIMIAAgA0ECaiABIAIQBEEIdkH/AXEQASMNIAA2AgQjDSABNgIMIAAgA0EDaiABIAIQBEH/AXEQASACQQFqIQIMAQsLIw1BFGokDSAAC9cHAgt/A34jDUE8ayQNEAUjDUEAQTz8CwAjDSABNgIAAkACQCABEANBDEcNACMNIAM2AgAgAxADQRBHDQAjDSAANgIAIw0gABAwIgg2AgQjDUEQEAYiADYCCCMNQRAQBiIONgIMIw0gCDYCACMNIAA2AhAjDSAONgIUIAggACAOEBcjDUEQEAYiDzYCGANAIAVBDEgEQCMNIA82AgAjDSABNgIQIA8gBSABIAUQAhABIAVBAWohBQwBCwsjDSAPNgIAIA9BD0EBEAEjDUEQEAYiADYCHCMNIAA2AgAjDSAONgIQIw0gBDYCFCMNIAQ2AiAgACAOIAQgBBADECgjDSAANgIAIw0gDjYCECMNIAI2AhQjDSACNgIgIAAgDiACIAIQAxAoIw1BEBAGIgE2AiQjDSAENgIAIAQQA6xCA4YhECMNIAI2AgAgAhADrEIDhiERA0AgCUEISARAIw0gATYCACABQQcgCWsgECAJQQN0rCISiKdB/wFxEAEjDSABNgIAIAFBDyAJayARIBKIp0H/AXEQASAJQQFqIQkMAQsLA0AgCkEQSARAIw0gADYCACMNIAA2AhAgACAKEAIhBCMNIAE2AhAgACAKIAEgChACIARzEAEgCkEBaiEKDAELCyMNIAA2AgAjDSAONgIQIAAgDhApIw1BEBAGIgE2AigjDSAINgIAIw0gDzYCECMNIAE2AhQgCCAPIAEQFyMNQRAQBiIENgIsA0AgC0EQSARAIw0gBDYCACMNIAA2AhAgACALEAIhBSMNIAE2AhAgBCALIAEgCxACIAVzQf8BcRABIAtBAWohCwwBCwsDQCAGQRBIBEAjDSAENgIAIAQgBhACIQAjDSADNgIAIAcgAyAGEAIgAHNyIQcgBkEBaiEGDAELCyAHQf8BcQ0AIw0gAjYCACMNIAIQAxAGIgA2AjAjDUEQEAYiAzYCNANAIA1BEEgEQCMNIAM2AgAjDSAPNgIQIAMgDSAPIA0QAhABIA1BAWohDQwBCwsjDSADNgIAIAMQJSMNQRAQBiIENgI4A0AjDSACNgIAIAIQAyAMSgRAIw0gCDYCACMNIAM2AhAjDSAENgIUIAggAyAEEBcjDSACNgIAIAIQAyAMa0EQTgR/QRAFIw0gAjYCACACEAMgDGsLIQVBACEBA0AgASAFSARAIw0gADYCACMNIAI2AhAgAiABIAxqIgYQAiEHIw0gBDYCECAAIAYgBCABEAIgB3NB/wFxEAEgAUEBaiEBDAELCyAMQRBqIQwjDSADNgIAIAMQJQwBCwsMAQtBACEACyMNQTxqJA0gAAviCQEMfyMNQRBrJA0QBSMNQgA3AwAjDUIANwMIIw1BEBAGIgM2AgADQCAEQRBIBEAjDSADNgIEIw0gATYCCCADIAQgASAEEAIQASAEQQFqIQQMAQsLQQAhAQNAIAFBBEgEQCMNIAA2AgQgACABEAQhBCMNIAM2AgQjDSADNgIIIAMgAUECdCIFIAMgBRACIARBGHZzEAEjDSADNgIEIw0gAzYCCCADIAVBAWoiBiADIAYQAiAEQRB2cxABIw0gAzYCBCMNIAM2AgggAyAFQQJqIgYgAyAGEAIgBEEIdnMQASMNIAM2AgQjDSADNgIIIAMgBUEDaiIFIAMgBRACIARzEAEgAUEBaiEBDAELC0EBIQQDQCAEQQ5MBEBBACEBA0AgAUEQSARAIw0gAzYCBCMNQdAcNgIIIw0gAzYCDCADIAFB0BwgAyABEAIQChABIAFBAWohAQwBCwsjDSADNgIEIANBARACIQEjDSADNgIEIw0gAzYCCCADQQEgA0EFEAIQASMNIAM2AgQjDSADNgIIIANBBSADQQkQAhABIw0gAzYCBCMNIAM2AgggA0EJIANBDRACEAEjDSADNgIEIANBDSABEAEjDSADNgIEIANBAhACIQEjDSADNgIEIANBBhACIQUjDSADNgIEIw0gAzYCCCADQQIgA0EKEAIQASMNIAM2AgQjDSADNgIIIANBBiADQQ4QAhABIw0gAzYCBCADQQogARABIw0gAzYCBCADQQ4gBRABIw0gAzYCBCADQQ8QAiEBIw0gAzYCBCMNIAM2AgggA0EPIANBCxACEAEjDSADNgIEIw0gAzYCCCADQQsgA0EHEAIQASMNIAM2AgQjDSADNgIIIANBByADQQMQAhABIw0gAzYCBCADQQMgARABIARBDkgEQEEAIQEDQCABQQRIBEAjDSADNgIEIAMgAUECdCIIEAIhCyMNIAM2AgQgAyAIQQFqIgUQAiEMIw0gAzYCBCADIAhBAmoiBhACIQkjDSADNgIEIAMgCEEDaiIHEAIiCiALIAxzIg0gCXNzIQ4jDSADNgIEIAMgCCANQf8BcUEHdkEbbCANQQF0c0H/AXEgCyAOc3NB/wFxEAEjDSADNgIEIAMgBSAJIAxzIgVB/wFxQQd2QRtsIAVBAXRzQf8BcSAMIA5zc0H/AXEQASMNIAM2AgQgAyAGIAkgCnMiBUH/AXFBB3ZBG2wgBUEBdHNB/wFxIAkgDnNzQf8BcRABIw0gAzYCBCADIAcgCiALcyIFQf8BcUEHdkEbbCAFQQF0c0H/AXEgCiAOc3NB/wFxEAEgAUEBaiEBDAELCwtBACEBA0AgAUEESARAIw0gADYCBCAAIARBAnQgAWoQBCEFIw0gAzYCBCMNIAM2AgggAyABQQJ0IgYgAyAGEAIgBUEYdnMQASMNIAM2AgQjDSADNgIIIAMgBkEBaiIHIAMgBxACIAVBEHZzEAEjDSADNgIEIw0gAzYCCCADIAZBAmoiByADIAcQAiAFQQh2cxABIw0gAzYCBCMNIAM2AgggAyAGQQNqIgYgAyAGEAIgBXMQASABQQFqIQEMAQsLIARBAWohBAwBCwtBACEAA0AgAEEQSARAIw0gAjYCBCMNIAM2AgggAiAAIAMgABACEAEgAEEBaiEADAELCyMNQRBqJA0LPwAjDUEEayQNEAUjDUEANgIAIw0gADYCACABIABBFGsoAhBBAXZPBH9BfwUgACABQQF0ai8BAAsjDUEEaiQNCw0AIABBFGsoAhBBAnYLjgEBAn8gAUGAAkkEfyABQQR2BUEfIAEQGyIBZ2siA0EHayECIAEgA0EEa3ZBEHMLIQEgACACQQJ0aigCBEF/IAF0cSIBBH8gACABaCACQQR0akECdGooAmAFIAAoAgBBfyACQQFqdHEiAQR/IAAgACABaCIAQQJ0aigCBGggAEEEdGpBAnRqKAJgBUEACwsLHQAgAEEBQRsgAGdrdGpBAWsgACAAQf7///8BSRsLlwEBAn8/ACIAQQBMBH9BASAAa0AAQQBIBUEACwRAAAtBsKACQQA2AgBB0KwCQQA2AgADQCABQRdJBEAgAUECdEGwoAJqQQA2AgRBACEAA0AgAEEQSQRAIAFBBHQgAGpBAnRBsKACakEANgJgIABBAWohAAwBCwsgAUEBaiEBDAELC0GwoAJB1KwCPwCsQhCGEB1BsKACJAoLhgEBA38gAUETakFwcUEEayEBIAAoAqAMIgMEQCABQRBrIgUgA0YEQCADKAIAIQQgBSEBCwsgAqdBcHEgAWsiA0EUSQRADwsgASAEQQJxIANBCGsiA0EBcnI2AgAgAUEANgIEIAFBADYCCCABQQRqIANqIgNBAjYCACAAIAM2AqAMIAAgARARC24BAn8jACIABEAgABAICyMLIgAEQCAAEAgLQZAREAhB4BIQCEGwFxAIQYAaEAhB0BwQCEGgHRAIQaALEAhB8AgQCEHgCRAIIwUiARALIQADQCAAIAFHBEAgABANGiAAQRRqEBQgABALIQAMAQsLCxIAIAAgASAAKAIEQQNxcjYCBAsSACAAIAAoAgRBfHEgAXI2AgQLKQEBfyABKAIIIQMgACABIAJyNgIEIAAgAzYCCCADIAAQHyABIAA2AggLDQAgACgCAEF8cUEEagsJACAAKAIAEAgLEQAgACABNgIAIAAgAUEAEA4LZgEBfyMNQQhrJA0QBSMNQgA3AwBBDyEBA0AgAUEMTgRAAkAjDSAANgIAIw0gADYCBCAAIAEgACABEAJBAWpB/wFxEAEjDSAANgIAIAAgARACDQAgAUEBayEBDAILCwsjDUEIaiQNC9wEAQd/Iw1BJGskDRAFIw1BAEEk/AsAIw0gADYCACMNIAA2AgQgABADQcAASgRAIw0gADYCBCMNIAAQFSIANgIACyMNQcAAEAYiCDYCCANAIw0gADYCBCAAEAMgAkoEQCMNIAg2AgQjDSAANgIMIAggAiAAIAIQAhABIAJBAWohAgwBCwsjDUHAABAGIgA2AhAjDUHAABAGIgI2AhQDQCADQcAASARAIw0gADYCBCMNIAg2AgwgACADIAggAxACQdwAc0H/AXEQASMNIAI2AgQjDSAINgIMIAIgAyAIIAMQAkE2c0H/AXEQASADQQFqIQMMAQsLIw0gAjYCBCMNIAIQAyEIIw0gATYCBCABEAMgCGoQBiIDNgIYA0AjDSACNgIEIAIQAyAESgRAIw0gAzYCBCMNIAI2AgwgAyAEIAIgBBACEAEgBEEBaiEEDAELCwNAIw0gATYCBCABEAMgBUoEQCMNIAM2AgQjDSACNgIMIAIQAyAFaiEEIw0gATYCDCADIAQgASAFEAIQASAFQQFqIQUMAQsLIw0gAzYCBCMNIAMQFSIBNgIcIw0gADYCBCMNIAAQAyEDIw0gATYCBCABEAMgA2oQBiICNgIgA0AjDSAANgIEIAAQAyAGSgRAIw0gAjYCBCMNIAA2AgwgAiAGIAAgBhACEAEgBkEBaiEGDAELCwNAIw0gATYCBCABEAMgB0oEQCMNIAI2AgQjDSAANgIMIAAQAyAHaiEDIw0gATYCDCACIAMgASAHEAIQASAHQQFqIQcMAQsLIw0gAjYCBCACEBUjDUEkaiQNC6IDAQZ/Iw1BGGskDRAFIw1BAEEY/AsAIw0gATYCACMNIAA2AgQjDSABIAAQJiIGNgIIIw1BIBAGIgQ2AgwjDUEAEAYiADYCEEEBIQUDQCADQSBIBEAjDSAANgIAIw0gABADIQcjDSACNgIAIAIQAyAHakEBahAGIgc2AhRBACEBA0AjDSAANgIAIAAQAyABSgRAIw0gBzYCACMNIAA2AgQgByABIAAgARACEAEgAUEBaiEBDAELC0EAIQEDQCMNIAI2AgAgAhADIAFKBEAjDSAHNgIAIw0gADYCBCAAEAMgAWohCCMNIAI2AgQgByAIIAIgARACEAEgAUEBaiEBDAELCyMNIAc2AgAjDSAHNgIEIAcgBxADQQFrIAVB/wFxEAEjDSAGNgIAIw0gBzYCBCMNIAYgBxAmIgA2AhAjDSAANgIAIAAQA7dBICADa7ek/AIhB0EAIQEDQCABIAdIBEAjDSAENgIAIw0gADYCBCAEIAEgA2ogACABEAIQASABQQFqIQEMAQsLIAMgB2ohAyAFQQFqIQUMAQsLIw1BGGokDSAEC5sBAQR/Iw1BCGskDRAFIw1CADcDAANAIAMgBUoEQEEQIAMgBWsiBCAEQRBOGyEGQQAhBANAIAQgBkgEQCMNIAA2AgAjDSAANgIEIAAgBBACIQcjDSACNgIEIAAgBCACIAQgBWoQAiAHcxABIARBAWohBAwBCwsjDSAANgIAIw0gATYCBCAAIAEQKSAFQRBqIQUMAQsLIw1BCGokDQuHAwEHfyMNQRBrJA0QBSMNQgA3AwAjDUIANwMIIw1BEBAGIgc2AgAjDUEQEAYiCDYCBANAIAJBEEgEQCMNIAg2AggjDSAANgIMIAggAiAAIAIQAhABIAJBAWohAgwBCwsDQCAFQYABSARAIw0gATYCCCABIAVBA3YQAkEHIAVBB3FrQQdxdkEBcQRAQQAhAgNAIAJBEEgEQCMNIAc2AggjDSAHNgIMIAcgAhACIQMjDSAINgIMIAcgAiAIIAIQAiADcxABIAJBAWohAgwBCwsLQQAhAkEAIQYDQCAGQRBIBEAjDSAINgIIIAggBhACQQFxIw0gCDYCCCMNIAg2AgwgCCAGIAJBB3QgCCAGEAJBAXZyQf8BcRABIQIgBkEBaiEGDAELCyACBEAjDSAINgIIIw0gCDYCDCAIQQAgCEEAEAJB4QFzEAELIAVBAWohBQwBCwsDQCAEQRBIBEAjDSAANgIIIw0gBzYCDCAAIAQgByAEEAIQASAEQQFqIQQMAQsLIw1BEGokDQssAD8AQRB0QaygAmtBAXYkAkHQChASJAVB8AoQEiQHQYAMEBIkCUEAEAYkCwuTAgEDfyABQfz///8DSwRAQeAJQbAMQc0DQR0QAAALIABBDCABQRNqQXBxQQRrIAFBDE0bIgMQGiIBRQRAQQQgACgCoAw/ACIBQRB0QQRrR3QgAxAbIAMgA0GAAk8bakH//wNqQYCAfHFBEHYhAiABIAIgASACShtAAEEASARAIAJAAEEASARAAAsLIAAgAUEQdD8ArEIQhhAdIAAgAxAaIQELIAEoAgAaIAAgARAQIAEoAgAiAkF8cSADayIEQRBPBEAgASADIAJBAnFyNgIAIAFBBGogA2oiAiAEQQRrQQFyNgIAIAAgAhARBSABIAJBfnE2AgAgAUEEaiABKAIAQXxxaiIAIAAoAgBBfXE2AgALIAEL/wIBAn8CQAJAAkACQCMDDgMAAQIDC0EBJANBACQEEB4jByQGIwQPCyMIRSEBIwYQCyEAA0AgACMHRwRAIAAkBiAAEA0gAUcEQCAAIAEQIEEAJAQgAEEUahAUIwQPCyAAEAshAAwBCwtBACQEEB4jBhALIwdGBEAjDSEAA0AgAEGsoAJJBEAgACgCABAIIABBBGohAAwBCwsjBhALIQADQCAAIwdHBEAgABANIAFHBEAgACABECAgAEEUahAUCyAAEAshAAwBCwsjCSEAIwckCSAAJAcgASQIIAAQCyQGQQIkAwsjBA8LIwYiACMHRwRAIAAQCyQGIAAQDRogAEGsoAJJBEAgAEEANgIEIABBADYCCAUjASAAECJrJAEgAEEEaiIAQaygAk8EQCMKRQRAEBwLIABBBGshASAAQQ9xQQEgABsEf0EBBSABKAIAQQFxCxogASABKAIAQQFyNgIAIwogARARCwtBCg8LIwcjBzYCBCMHIwc2AghBACQDC0EAC7YBAQF/Iw1BEGskDRAFIw1CADcDACMNQgA3AwggAEUEQCMNQQxBAxAMIgA2AgALIw0gADYCBCAAQQAQJCMNIAA2AgQgAEEANgIEIw0gADYCBCAAQQA2AgggAUH8////A0sEQEHwCEGgCUETQTkQAAALIw0gAUEBEAwiAjYCCCMNIAA2AgQjDSACNgIMIAAgAhAkIw0gADYCBCAAIAI2AgQjDSAANgIEIAAgATYCCCMNQRBqJA0gAAvwAQEDfyMNQQRrJA0QBSMNQQA2AgAjDSAANgIAIAEgACgCCCICQQJ2SwRAIAFB/////wBLBEBB8AhB0B1BE0EwEAAACyMNIAA2AgACQEH8////AyACQQF0IgIgAkH8////A08bIgJBCCABIAFBCE0bQQJ0IgEgASACSRsiAyAAKAIAIgJBFGsiBCgCAEF8cUEQa00EQCAEIAM2AhAgAiEBDAELIAMgBCgCDBAMIgEgAiADIAQoAhAiBCADIARJG/wKAAALIAEgAkcEQCAAIAE2AgAgACABNgIEIAAgAUEAEA4LIAAgAzYCCAsjDUEEaiQNC/8HAQp/Iw1BDGskDRAFIw1CADcDACMNQQA2AggjDUHAABAPIgw2AgADQCAEQRBIBEAjDSAMNgIEIw0gATYCCCABIAIgBEECdGoiBRACQRh0Iw0gATYCCCABIAVBAWoQAkEQdHIjDSABNgIIIAEgBUECahACQQh0ciEDIw0gATYCCCAMIAQgASAFQQNqEAIgA3IQByAEQQFqIQQMAQsLQRAhBANAIARBwABIBEAjDSAMNgIEIAwgBEEPayIDEAQhAiMNIAw2AgQgDCADEAQhASMNIAw2AgQgAkEZdCACQQd2ciABQQ50IAFBEnZycyAMIAMQBEEDdnMhBSMNIAw2AgQgDCAEQQJrIgMQBCECIw0gDDYCBCAMIAMQBCEBIw0gDDYCBCACQQ90IAJBEXZyIAFBDXQgAUETdnJzIAwgAxAEQQp2cyECIw0gDDYCBCMNIAw2AgggDCAEQRBrEAQgBWohASMNIAw2AgggDCAEIAwgBEEHaxAEIAFqIAJqEAcgBEEBaiEEDAELCyMNIAA2AgQgAEEAEAQhCCMNIAA2AgQgAEEBEAQhBCMNIAA2AgQgAEECEAQhAyMNIAA2AgQgAEEDEAQhBiMNIAA2AgQgAEEEEAQhByMNIAA2AgQgAEEFEAQhAiMNIAA2AgQgAEEGEAQhASMNIAA2AgQgAEEHEAQhBQNAIAtBwABIBEAjDUGAGjYCBCMNQQRrJA0QBSMNQQA2AgAjDUGAGjYCACALQYwaKAIATwRAQaALQdAdQfIAQSoQAAALIw1BgBo2AgBBhBooAgAgC0ECdGooAgAhCSMNQQRqJA0jDSAMNgIEIAwgCxAEIAdBB3QgB0EZdnIgB0EadCAHQQZ2ciAHQRV0IAdBC3Zyc3MgBWogAiAHcSAHQX9zIAFxc2ogCWpqIQogCEEKdCAIQRZ2ciAIQR50IAhBAnZyIAhBE3QgCEENdnJzcyADIARxIAQgCHEgAyAIcXNzaiABIQUgAiEBIAchAiAGIApqIQcgAyEGIAQhAyAIIQQgCmohCCALQQFqIQsMAQsLIw0gADYCBCMNIAA2AgggAEEAIABBABAEIAhqEAcjDSAANgIEIw0gADYCCCAAQQEgAEEBEAQgBGoQByMNIAA2AgQjDSAANgIIIABBAiAAQQIQBCADahAHIw0gADYCBCMNIAA2AgggAEEDIABBAxAEIAZqEAcjDSAANgIEIw0gADYCCCAAQQQgAEEEEAQgB2oQByMNIAA2AgQjDSAANgIIIABBBSAAQQUQBCACahAHIw0gADYCBCMNIAA2AgggAEEGIABBBhAEIAFqEAcjDSAANgIEIw0gADYCCCAAQQcgAEEHEAQgBWoQByMNQQxqJA0L6AMBBH8jDUEMayQNEAUjDUIANwMAIw1BADYCCCMNQTwQDyICNgIAA0AgAUEISARAIw0gAjYCBCMNIAA2AgggACABQQJ0IgMQAkEYdCMNIAA2AgggACADQQFqEAJBEHRyIw0gADYCCCAAIANBAmoQAkEIdHIhBCMNIAA2AgggAiABIAAgA0EDahACIARyEAcgAUEBaiEBDAELC0EIIQADQCAAQTxIBEAjDSACNgIEIAIgAEEBaxAEIQEgAEEHcQR/IABBCG9BBEYEfyMNQdAcNgIEQdAcIAFBGHYQCkEYdCMNQdAcNgIEQdAcIAFBEHZB/wFxEApBEHRyIw1B0Bw2AgRB0BwgAUEIdkH/AXEQCkEIdHIhAyMNQdAcNgIEQdAcIAFB/wFxEAogA3IFIAELBSMNQdAcNgIEQdAcIAFBCHQgAUEYdnIiAUEYdhAKQRh0Iw1B0Bw2AgRB0BwgAUEQdkH/AXEQCkEQdHIjDUHQHDYCBEHQHCABQQh2Qf8BcRAKQQh0ciEDIw1B0Bw2AgRB0BwgAUH/AXEQCiADciMNQaAdNgIEQaAdIABBCG0QCkEYdHMLIQEjDSACNgIEIw0gAjYCCCACIAAgAiAAQQhrEAQgAXMQByAAQQFqIQAMAQsLIw1BDGokDSACC2EBAn8jDUEEayQNEAUjDUEANgIAIw1BAEEBEAwiAEGAHkEA/AoAACAANgIAQRBBBRAMIgEgADYCACABIABBABAOIAEgADYCBCABQQA2AgggAUEANgIMIw1BBGokDSABJAALDAAgACABaiACOgAAC6QBAQN/Iw1BDGskDRAFIw1CADcDACMNQQA2AggjDSAAEAYiAzYCACMNIwAiAjYCBCMNIAM2AggjDUEEayQNEAUjDUEANgIAIw0gAjYCACACIAIoAgwiAEEBaiIBEC4jDSACNgIAIAIoAgQgAEECdGogAzYCACACIANBARAOIw0gAjYCACACIAE2AgwjDUEEaiQNIw0gAzYCBCADKAIEIw1BDGokDQvPBQAjDUE8ayQNEAUjDUEAQTz8CwAjDSAAIAEQCSIBNgIAIw0gAiADEAkiAjYCBCMNIAQgBRAJIgM2AggjDSAGIAcQCSIFNgIMIw0gCCAJEAkiBjYCECMNQYABEAYiBzYCFEEAIQADQCAAQYABSARAIw0gBzYCGCMNQZARNgIcIw1BsBc2AiAjDUEEayQNEAUjDUEANgIAIw1BsBc2AgAgAEG8FygCAE8EQEGgC0HQHUHyAEEqEAAACyMNQbAXNgIAQbQXKAIAIABBAnRqKAIAIQQjDUEEaiQNQZARIAQQCiEEIw1B4BI2AhwgByAAQeASIAAQCiAEc0H/AXEQASAAQQFqIQAMAQsLIw0gATYCGCMNIAEQAyEEIw0gAjYCGCACEAMgBGoQBiIANgIkQQAhBANAIw0gATYCGCABEAMgBEoEQCMNIAA2AhgjDSABNgIcIAAgBCABIAQQAhABIARBAWohBAwBCwtBACEEA0AjDSACNgIYIAIQAyAESgRAIw0gADYCGCMNIAE2AhwgARADIARqIQgjDSACNgIcIAAgCCACIAQQAhABIARBAWohBAwBCwsjDUEVEAYiBDYCKEEAIQIDQCACQRVIBEAjDSAENgIYIAQgAkHgHiACEBhB/wFxEAEgAkEBaiECDAELCyMNIAc2AhgjDSAANgIcIw0gBDYCICMNIAcgACAEECciADYCLEEAIQIDQCACQYABSARAIw0gBzYCGCAHIAJBABABIAJBAWohAgwBCwsjDSAANgIYIw0gAzYCHCMNIAU2AiAjDSAGNgIwIw0gATYCNCMNIAAgAyAFIAYgARAWIgI2AjhBACEBA0AjDSAANgIYIAAQAyABSgRAIw0gADYCGCAAIAFBABABIAFBAWohAQwBCwsgAkUEQEEAJAwjDUE8aiQNQX8PCyACJAtBASQMIw0jCyIANgIYIAAQAyMNQTxqJA0LCgAgACABai0AAAubBgEIfyMNQdgAayQNEAUjDUEAQdgA/AsAAn8CQCMMRQ0AIw0gACABEAkiATYCACMNIAIgAxAJIgI2AgQjDSAEIAUQCSIDNgIIIw0gBiAHEAkiBDYCDCMNIAggCRAJIgU2AhAjDSAKIAsQCSIGNgIUIw0gDCANEAkiBzYCGCMNIA4gDxAJIgg2AhwjDSAQIBEQCSIJNgIgIw0gEiATEAkiCjYCJCMNIAE2AigjDSABEAMhCyMNIAI2AiggAhADIAtqIQsjDSADNgIoIAMQAyALahAGIgs2AiwDQCMNIAE2AiggARADIBhKBEAjDSALNgIoIBUiAEEBaiEVIw0gATYCMCALIAAgASAYEAIQASAYQQFqIRgMAQsLA0AjDSACNgIoIAIQAyAZSgRAIw0gCzYCKCAVIgBBAWohFSMNIAI2AjAgCyAAIAIgGRACEAEgGUEBaiEZDAELCwNAIw0gAzYCKCADEAMgGkoEQCMNIAs2AiggFSIAQQFqIRUjDSADNgIwIAsgACADIBoQAhABIBpBAWohGgwBCwsjDUEOEAYiADYCNANAIBZBDkgEQCMNIAA2AiggACAWQeAfIBYQGEH/AXEQASAWQQFqIRYMAQsLIw0jCyIBNgIoIw0gCzYCMCMNIAA2AjgjDSABIAsgABAnIgA2AjwjDSAANgIoIw0gBTYCMCMNIAY2AjgjDSAHNgJAIw0gBDYCRCMNIAAgBSAGIAcgBBAWIgE2AkgDQCMNIAA2AiggABADIBtKBEAjDSAANgIoIAAgG0EAEAEgG0EBaiEbDAELCyABRQ0AIw0gATYCKCMNIAg2AjAjDSAJNgI4Iw0gCjYCQCMNIAQ2AkQjDSABIAggCSAKIAQQFiIANgJMIw0gATYCUANAIw0gATYCKCABEAMgHEoEQCMNIAE2AiggASAcQQAQASAcQQFqIRwMAQsLIABFDQAjDSAANgJUA0AjDSAANgIoIAAQAyAXSgRAIw0gADYCKCAUIBdqIAAgFxACOgAAIBdBAWohFwwBCwsjDSAANgIoIAAQAwwBC0F/CyMNQdgAaiQNC1UBAn8jDUEEayQNEAUjDUEANgIAA0AjDSMLIgE2AgAgARADIABKBEAjDSMLIgE2AgAgASAAQQAQASAAQQFqIQAMAQsLQQAQBiQLQQAkDCMNQQRqJA0LC78VNwBBjAgLARwAQZgICwEBAEGsCAsBLABBuAgLDgUAAAAQAAAAIAQAACAEAEHcCAsBLABB6AgLIwIAAAAcAAAASQBuAHYAYQBsAGkAZAAgAGwAZQBuAGcAdABoAEGMCQsBPABBmAkLLQIAAAAmAAAAfgBsAGkAYgAvAGEAcgByAGEAeQBiAHUAZgBmAGUAcgAuAHQAcwBBzAkLATwAQdgJCy8CAAAAKAAAAEEAbABsAG8AYwBhAHQAaQBvAG4AIAB0AG8AbwAgAGwAYQByAGcAZQBBjAoLATwAQZgKCycCAAAAIAAAAH4AbABpAGIALwByAHQALwBpAHQAYwBtAHMALgB0AHMAQYwLCwE8AEGYCwsrAgAAACQAAABJAG4AZABlAHgAIABvAHUAdAAgAG8AZgAgAHIAYQBuAGcAZQBBzAsLASwAQdgLCxsCAAAAFAAAAH4AbABpAGIALwByAHQALgB0AHMAQZwMCwE8AEGoDAslAgAAAB4AAAB+AGwAaQBiAC8AcgB0AC8AdABsAHMAZgAuAHQAcwBB3AwLAhwCAEHoDAuIBAEAAAAAAgAAs7NRbUhGnCsIYZ1FPcVF/eV1IcUEIHl8VBGGBU53LQn/gh9GEjakUwVM/wujbQ3OmORib0muxkhCL0VpRDFBZo+iKwJvg2lpjHkZ2uoqxmVpDLFwq/vAXR5c1dWeGPz77lPWADnATWKPq6zbOTRRXgBH4ZaTMv/jtjhiHFExqz+j13elR/05qHUukVgY+O7x3TzdaWKtR2aNxXCwLRo37h25FMaH0fL54z5IpvhRAc5bTTXZ8GzZ84ZHF1TCu6gPDdEOIzecJAt5RkRP1p697FGmUOl0/QO7yg5P6tDFxMBSGZEFwKdcqlMPmjC9HPA1kx7YMOqaw2V7Ai6AeYFSesMJX7Pi+FenanRczfj7p7ailDP3j1wU0gPkMY5VHkwlXnXi9/FEdjt10m6VIJGeKjfQ4g9wFNKMlvlqseEDSZMlb3YpRY4r/VJd3zrZXR2SjXs8ypGxmZ8vLwCI1pnG7SqC3o85eyvw6kmi9W68QJ77hIF8Vq4C+Jzmzvv1Mg7xCKOQv1O13+dAlzTruI8kix0vNQjnoN2CP6yu12m/kgSmbjqkra93LIZ0JjtVZBXEP+AQfE78VWIbWKc8tLCXnVEc5gzMj/8HivztP+MeDV2MhMiZAgG6lAk1TGGulBia1WGkIx2NX5XhwWRFR89JkOL5A+y9GPvaIXUjwIOWCbgAQfwQCwEsAEGIEQsWBgAAABAAAABwBgAAcAYAAAACAAAAAgBBrBELAZwAQbgRC4gBAQAAAIAAAACH5wGKdPpiKAw3CSgbl0A/Wvwb4Hliiv2w11LB20+AZy++sSfk0ZUlhM7oSi83khL+6efHwHFo/OutaRLUa8jdSAlpkqaezBi1SGTbyBlHTC6MGkW75n5tqO3cif3LLxVClduBQLdLK1/70TYuDucqhEdPanZTKI9QX759igok8ABBzBILASwAQdgSCxUGAAAAEAAAAMAIAADACAAAgAAAAIAAQfwSCwIcAgBBiBMLhQQBAAAAAAIAAA8AAACGAQAAFgAAAAABAACcAAAA7AAAAKoBAAAjAAAAIQEAABQAAAAgAQAAZgAAAAkAAABiAAAAeQAAADMAAAAtAAAAFAEAAMABAABpAAAAkwEAADABAADSAQAAegEAAFsBAADwAAAA6wAAACsBAACOAAAAbAAAAIcBAAACAAAAKgEAAO4AAAC2AAAAyQAAAOABAADdAQAAxAEAAAMAAABtAQAACgAAAGsAAAAbAAAA5gEAAAsAAABnAQAAlgAAAI0BAAB4AAAAbwEAAE8BAAC0AAAAPQEAAAEBAADcAQAAigAAAJsBAABuAAAAhAAAAL8BAACLAAAA0QAAAIMBAADOAQAAlwAAAF0AAACvAQAAXAEAAA0BAADTAQAASAEAAP0AAACRAQAAHAEAAIAAAABVAAAAkwAAANkAAAD6AQAAJgEAAIsBAACIAAAAYAEAABcBAAC9AQAAfgEAAMQAAACnAAAAgwAAAFwAAABfAQAA1gEAALUBAABTAAAA1AAAAE0AAAAFAQAAfgAAAO0BAADyAQAAGwEAAMsBAABsAQAAhgAAAJkBAAB3AAAAVwAAAO0AAAAKAQAAyAEAAP8AAABgAAAAfQEAAMcBAABGAQAAxgAAACQAAAAZAAAAGQEAAEoAAACJAAAAjwAAADUBAADfAAAAJQEAAPkBAAD7AEGcFwsBLABBqBcLFQcAAAAQAAAAkAkAAJAJAAAAAgAAgABBzBcLAhwBAEHYFwuIAgEAAAAAAQAAmC+KQpFEN3HP+8C1pdu16VvCVjnxEfFZpII/ktVeHKuYqgfYAVuDEr6FMSTDfQxVdF2+cv6x3oCnBtybdPGbwcFpm+SGR77vxp3BD8yhDCRvLOktqoR0StypsFzaiPl2UlE+mG3GMajIJwOwx39Zv/ML4MZHkafVUWPKBmcpKRSFCrcnOCEbLvxtLE0TDThTVHMKZbsKanYuycKBhSxykqHov6JLZhqocItLwqNRbMcZ6JLRJAaZ1oU1DvRwoGoQFsGkGQhsNx5Md0gntbywNLMMHDlKqthOT8qcW/NvLmjugo90b2OleBR4yIQIAseM+v++kOtsUKT3o/m+8nhxxgBB7BkLASwAQfgZCxUIAAAAEAAAAOALAADgCwAAAAEAAEAAQZwaCwIcAQBBqBoLiAIBAAAAAAEAAGN8d3vya2/FMAFnK/7Xq3bKgsl9+llH8K3Uoq+cpHLAt/2TJjY/98w0peXxcdgxFQTHI8MYlgWaBxKA4usnsnUJgywaG25aoFI71rMp4y+EU9EA7SD8sVtqy745SkxYz9DvqvtDTTOFRfkCf1A8n6hRo0CPkp049by22iEQ//PSzQwT7F+XRBfEp349ZF0Zc2CBT9wiKpCIRu64FN5eC9vgMjoKSQYkXMLTrGKRleR558g3bY3VTqlsVvTqZXquCLp4JS4cprTG6N10H0u9i4pwPrVmSAP2DmE1V7mGwR2e4fiYEWnZjpSbHofpzlUo34yhiQ2/5kJoQZktD7BUuxYAQbwcCwEsAEHIHAsWBgAAABAAAAAwDQAAMA0AAAABAAAAAQBB7BwLARwAQfgcCxMBAAAACwAAAAABAgQIECBAgBs2AEGMHQsBLABBmB0LFQYAAAAQAAAAgA4AAIAOAAALAAAACwBBvB0LASwAQcgdCyECAAAAGgAAAH4AbABpAGIALwBhAHIAcgBhAHkALgB0AHMAQewdCwEcAEH4HQsBAQBBjB4LATwAQZgeCysCAAAAJAAAAH4AbABpAGIALwB0AHkAcABlAGQAYQByAHIAYQB5AC4AdABzAEHMHgsBPABB2B4LMQIAAAAqAAAAdgBpAGQAdQBrAGkAOgB3AHIAYQBwAC0AcABlAHAAcABlAHIAOgB2ADEAQYwfCwE8AEGYHwstAgAAACYAAAB+AGwAaQBiAC8AcwB0AGEAdABpAGMAYQByAHIAYQB5AC4AdABzAEHMHwsBLABB2B8LIwIAAAAcAAAAdgBpAGQAdQBrAGkAOgB3AHIAYQBwADoAdgAxAEGAIAsqCgAAACAAAAAgAAAAIAAAAAAAAABBAAAAAkEAAEIAAAACCQAAAgEAACQB"

    @Volatile
    private var makimaModule: WasmModule? = null

    @Volatile
    private var makimaExports: MakimaExports? = null

    @Volatile
    private var cachedVidukiServers: List<VidukiServer>? = null

    private fun getOrLoadMakimaModule(client: OkHttpClient): Pair<WasmModule, MakimaExports>? {
        makimaModule?.let { mod ->
            makimaExports?.let { exp ->
                return mod to exp
            }
        }
        synchronized(this) {
            makimaModule?.let { mod ->
                makimaExports?.let { exp ->
                    return mod to exp
                }
            }

            var loadedModule: WasmModule? = null
            var exports = MakimaExports()

            try {
                val manReq = Request.Builder()
                    .url("https://www.viduki.net/makima-manifest.json")
                    .header("Referer", "https://www.viduki.net/")
                    .header("User-Agent", USER_AGENT)
                    .build()
                val manResp = client.newCall(manReq).execute()
                if (manResp.isSuccessful) {
                    val manBody = manResp.body?.string().orEmpty()
                    val manObj = json.parseToJsonElement(manBody).jsonObject
                    val wasmRelUrl = manObj["url"]?.jsonPrimitive?.content ?: "/makima.2d8bf5c708fc07e2.wasm"
                    val expObj = manObj["exports"]?.jsonObject

                    val allocName = expObj?.get("alloc")?.jsonPrimitive?.content ?: "_pRhU"
                    val resetName = expObj?.get("reset")?.jsonPrimitive?.content ?: "_twc7"
                    val writeByteName = expObj?.get("writeByte")?.jsonPrimitive?.content ?: "_sywi"
                    val readByteName = expObj?.get("readByte")?.jsonPrimitive?.content ?: "_S02C"
                    val decPepperName = expObj?.get("decryptPepper")?.jsonPrimitive?.content ?: "_Uk9g"
                    val decEnvName = expObj?.get("decryptEnvelope")?.jsonPrimitive?.content ?: "_KejE"
                    val dropPepName = expObj?.get("dropPepper")?.jsonPrimitive?.content ?: "_9nwS"

                    exports = MakimaExports(allocName, resetName, writeByteName, readByteName, decPepperName, decEnvName, dropPepName)

                    val wasmFullUrl = if (wasmRelUrl.startsWith("http")) wasmRelUrl else "https://www.viduki.net$wasmRelUrl"
                    val wasmReq = Request.Builder()
                        .url(wasmFullUrl)
                        .header("Referer", "https://www.viduki.net/")
                        .header("User-Agent", USER_AGENT)
                        .build()
                    val wasmResp = client.newCall(wasmReq).execute()
                    if (wasmResp.isSuccessful) {
                        val wasmBytes = wasmResp.body?.bytes()
                        if (wasmBytes != null && wasmBytes.isNotEmpty()) {
                            loadedModule = Parser.parse(ByteArrayInputStream(wasmBytes))
                        }
                    }
                }
            } catch (ce: CancellationException) {
                throw ce
            } catch (t: Throwable) {
                safeLog("OneShowsWasmEngine", "getOrLoadMakimaModule live fetch error: ${t.message}", t)
            }

            if (loadedModule == null) {
                try {
                    val b64Bytes = Base64.getDecoder().decode(VIDUKI_WASM_B64)
                    loadedModule = Parser.parse(ByteArrayInputStream(b64Bytes))
                    exports = MakimaExports()
                } catch (ce: CancellationException) {
                    throw ce
                } catch (t: Throwable) {
                    safeLog("OneShowsWasmEngine", "getOrLoadMakimaModule embedded fallback error: ${t.message}", t)
                    return null
                }
            }

            val finalMod = loadedModule ?: return null
            makimaModule = finalMod
            makimaExports = exports
            return finalMod to exports
        }
    }

    suspend fun fetchVidukiServers(client: OkHttpClient): List<VidukiServer> = withContext(Dispatchers.IO) {
        cachedVidukiServers?.let { return@withContext it }
        try {
            val req = Request.Builder()
                .url("https://api.viduki.net/main/servers")
                .header("Referer", "https://www.viduki.net/")
                .header("Origin", "https://www.viduki.net")
                .header("Accept", "application/json")
                .header("User-Agent", USER_AGENT)
                .build()
            val body = client.newCall(req).execute().use { it.body?.string().orEmpty() }
            if (body.startsWith("[")) {
                val arr = json.parseToJsonElement(body).jsonArray
                val list = arr.mapNotNull { elem ->
                    val obj = elem.jsonObject
                    val name = obj["name"]?.jsonPrimitive?.contentOrNull ?: return@mapNotNull null
                    val lang = obj["language"]?.jsonPrimitive?.contentOrNull ?: "ENGLISH"
                    VidukiServer(name, lang)
                }
                if (list.isNotEmpty()) {
                    cachedVidukiServers = list
                    return@withContext list
                }
            }
        } catch (ce: CancellationException) {
            throw ce
        } catch (t: Throwable) {
            safeLog("OneShowsWasmEngine", "fetchVidukiServers error: ${t.message}", t)
        }
        val fallback = listOf(
            VidukiServer("Chris", "HINDI"),
            VidukiServer("Wesker", "HINDI"),
            VidukiServer("Grace", "HINDI"),
            VidukiServer("Leon", "ENGLISH"),
            VidukiServer("Jill", "ENGLISH"),
            VidukiServer("Ada", "ENGLISH"),
            VidukiServer("Claire", "ENGLISH"),
            VidukiServer("Rebecca", "ENGLISH"),
            VidukiServer("Sherry", "ENGLISH"),
            VidukiServer("Ethan", "ENGLISH"),
            VidukiServer("Ashley", "VIETNAM")
        )
        cachedVidukiServers = fallback
        fallback
    }

    suspend fun decryptVidukiMainStream(
        client: OkHttpClient,
        baseUrl: String,
        nonce: String,
        pathAndQuery: String
    ): String? = withContext(Dispatchers.IO) {
        try {
            val (module, exports) = getOrLoadMakimaModule(client) ?: return@withContext null

            val abortFn = HostFunction(
                "env",
                "abort",
                listOf(ValueType.I32, ValueType.I32, ValueType.I32, ValueType.I32),
                emptyList()
            ) { _, _ -> longArrayOf() }

            val importValues = ImportValues.builder()
                .withFunctions(listOf(abortFn))
                .build()

            val instance = Instance.builder(module)
                .withImportValues(importValues)
                .build()

            val alloc = instance.export(exports.alloc)
            val decryptPepper = instance.export(exports.decryptPepper)
            val decryptEnvelope = instance.export(exports.decryptEnvelope)
            val memory = instance.memory()

            fun allocAndWrite(bytes: ByteArray): Int {
                val ptr = alloc.apply(bytes.size.toLong())[0].toInt()
                memory.write(ptr, bytes)
                return ptr
            }

            fun readBytesFromMemory(ptr: Int, len: Int): ByteArray {
                return memory.readBytes(ptr, len)
            }

            // Pepper handshake
            val chReq = Request.Builder()
                .url("$baseUrl/altcha-challenge")
                .header("Referer", "https://www.viduki.net/")
                .header("Origin", "https://www.viduki.net")
                .header("User-Agent", USER_AGENT)
                .build()
            val chBody = client.newCall(chReq).execute().use { it.body?.string().orEmpty() }
            val chObj = json.parseToJsonElement(chBody).jsonObject
            val salt = chObj["salt"]?.jsonPrimitive?.content ?: return@withContext null
            val target = chObj["challenge"]?.jsonPrimitive?.content ?: return@withContext null
            val maxNum = chObj["maxnumber"]?.jsonPrimitive?.content?.toLongOrNull() ?: 50000L
            val algo = chObj["algorithm"]?.jsonPrimitive?.content ?: "SHA-256"
            val sig = chObj["signature"]?.jsonPrimitive?.content ?: ""

            val altcha = solveAltcha(salt, target, maxNum, algo, sig)

            val pepReq = Request.Builder()
                .url("$baseUrl/pepper-key")
                .header("Referer", "https://www.viduki.net/")
                .header("Origin", "https://www.viduki.net")
                .header("User-Agent", USER_AGENT)
                .header("X-Nonce", nonce)
                .header("X-Altcha", altcha)
                .header("Accept", "application/json")
                .build()
            val pepBody = client.newCall(pepReq).execute().use { it.body?.string().orEmpty() }
            val pepObj = json.parseToJsonElement(pepBody).jsonObject
            val bucket = pepObj["bucket"]?.jsonPrimitive?.content?.toLongOrNull() ?: return@withContext null
            val pepIv = hexToBytes(pepObj["iv"]?.jsonPrimitive?.content ?: return@withContext null)
            val pepCt = hexToBytes(pepObj["ct"]?.jsonPrimitive?.content ?: return@withContext null)
            val pepTag = hexToBytes(pepObj["tag"]?.jsonPrimitive?.content ?: return@withContext null)

            val nonceBytes = hexToBytes(nonce)
            val bucketBuf = ByteBuffer.allocate(8).order(ByteOrder.BIG_ENDIAN).putLong(bucket).array()

            val pNonce = allocAndWrite(nonceBytes)
            val pBucket = allocAndWrite(bucketBuf)
            val pIv = allocAndWrite(pepIv)
            val pCt = allocAndWrite(pepCt)
            val pTag = allocAndWrite(pepTag)

            val pepRes = decryptPepper.apply(
                pNonce.toLong(), nonceBytes.size.toLong(),
                pBucket.toLong(), 8L,
                pIv.toLong(), pepIv.size.toLong(),
                pCt.toLong(), pepCt.size.toLong(),
                pTag.toLong(), pepTag.size.toLong()
            )[0].toInt()

            if (pepRes <= 0) return@withContext null

            // Query server
            val random = SecureRandom()
            val cnBytes = ByteArray(16).also { random.nextBytes(it) }
            val reqIdBytes = ByteArray(16).also { random.nextBytes(it) }
            val clientNonceHex = cnBytes.joinToString("") { "%02x".format(it) }
            val reqIdHex = reqIdBytes.joinToString("") { "%02x".format(it) }

            val targetUrl = "$baseUrl$pathAndQuery"
            val streamReq = Request.Builder().url(targetUrl)
                .header("Referer", "https://www.viduki.net/")
                .header("Origin", "https://www.viduki.net")
                .header("User-Agent", USER_AGENT)
                .header("X-Nonce", nonce)
                .header("X-Client-Nonce", clientNonceHex)
                .header("X-Request-Id", reqIdHex)
                .header("Accept", "application/json")
                .build()
            val streamResp = client.newCall(streamReq).execute()
            val streamBody = streamResp.body?.string().orEmpty()
            if (streamBody.isBlank()) return@withContext null

            val sObj = json.parseToJsonElement(streamBody).jsonObject
            if (sObj.containsKey("stream") || sObj.containsKey("links")) {
                return@withContext streamBody
            }

            val snHex = sObj["sn"]?.jsonPrimitive?.contentOrNull ?: return@withContext null
            val tb = sObj["tb"]?.jsonPrimitive?.contentOrNull?.toLongOrNull() ?: return@withContext null
            val iv1Hex = sObj["iv1"]?.jsonPrimitive?.contentOrNull ?: return@withContext null
            val iv2Hex = sObj["iv2"]?.jsonPrimitive?.contentOrNull ?: return@withContext null
            val tag1Hex = sObj["tag1"]?.jsonPrimitive?.contentOrNull ?: return@withContext null
            val tag2Hex = sObj["tag2"]?.jsonPrimitive?.contentOrNull ?: return@withContext null
            val wkHex = sObj["wk"]?.jsonPrimitive?.contentOrNull ?: return@withContext null
            val ctHex = sObj["ct"]?.jsonPrimitive?.contentOrNull ?: return@withContext null

            val snBytes = hexToBytes(snHex)
            val tbBuf = ByteBuffer.allocate(8).order(ByteOrder.BIG_ENDIAN).putLong(tb).array()
            val iv1Bytes = hexToBytes(iv1Hex)
            val iv2Bytes = hexToBytes(iv2Hex)
            val tag1Bytes = hexToBytes(tag1Hex)
            val tag2Bytes = hexToBytes(tag2Hex)
            val wkBytes = hexToBytes(wkHex)
            val ctBytes = hexToBytes(ctHex)

            val pCN = allocAndWrite(cnBytes)
            val pSN = allocAndWrite(snBytes)
            val pTB = allocAndWrite(tbBuf)
            val pReqId = allocAndWrite(reqIdBytes)
            val pIv2 = allocAndWrite(iv2Bytes)
            val pWk = allocAndWrite(wkBytes)
            val pTag2 = allocAndWrite(tag2Bytes)
            val pIv1 = allocAndWrite(iv1Bytes)
            val pSCt = allocAndWrite(ctBytes)
            val pTag1 = allocAndWrite(tag1Bytes)
            val pOut = alloc.apply(ctBytes.size.toLong())[0].toInt()

            val outLen = decryptEnvelope.apply(
                pCN.toLong(), cnBytes.size.toLong(),
                pSN.toLong(), snBytes.size.toLong(),
                pTB.toLong(), 8L,
                pReqId.toLong(), reqIdBytes.size.toLong(),
                pIv2.toLong(), iv2Bytes.size.toLong(),
                pWk.toLong(), wkBytes.size.toLong(),
                pTag2.toLong(), tag2Bytes.size.toLong(),
                pIv1.toLong(), iv1Bytes.size.toLong(),
                pSCt.toLong(), ctBytes.size.toLong(),
                pTag1.toLong(), tag1Bytes.size.toLong(),
                pOut.toLong()
            )[0].toInt()

            if (outLen <= 0) return@withContext null
            val decBytes = readBytesFromMemory(pOut, outLen)
            String(decBytes, Charsets.UTF_8)
        } catch (ce: CancellationException) {
            throw ce
        } catch (t: Throwable) {
            safeLog("OneShowsWasmEngine", "decryptVidukiMainStream error: ${t.message}", t)
            null
        }
    }

    suspend fun requestVidukiStream(
        client: OkHttpClient,
        serverName: String,
        isTv: Boolean,
        tmdbId: String,
        season: Int = 1,
        episode: Int = 1
    ): String? = withContext(Dispatchers.IO) {
        val baseUrl = "https://api.viduki.net"
        val nonce = getVidukiSessionNonce(client, baseUrl) ?: return@withContext null
        val path = if (isTv) "/main/tv/$tmdbId/$season/$episode?srv=$serverName" else "/main/movie/$tmdbId?srv=$serverName"
        val res = decryptVidukiMainStream(client, baseUrl, nonce, path)
        if (res != null) {
            try {
                val obj = json.parseToJsonElement(res).jsonObject
                obj["stream"]?.jsonObject?.get("url")?.jsonPrimitive?.contentOrNull
            } catch (_: Throwable) { null }
        } else null
    }

    suspend fun requestVidukiPremiumEmbeds(
        client: OkHttpClient,
        isTv: Boolean,
        tmdbId: String,
        season: Int = 1,
        episode: Int = 1
    ): String? = withContext(Dispatchers.IO) {
        val baseUrl = "https://api.viduki.net"
        val nonce = getVidukiSessionNonce(client, baseUrl) ?: return@withContext null
        val path = if (isTv) "/premium_embeds/tv/$tmdbId/$season/$episode" else "/premium_embeds/movie/$tmdbId"
        decryptVidukiMainStream(client, baseUrl, nonce, path)
    }

    fun prewarm(client: OkHttpClient) {
        try {
            getOrLoadMakimaDLModule(client)
            getOrLoadMakimaModule(client)
        } catch (_: Throwable) {}
    }
}
